/**
 * @fileoverview gRPC-Web generated client stub for ai_poi.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: ai_poi_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as common_pb from './common_pb'; // proto import: "common.proto"
import * as ai_poi_service_pb from './ai_poi_service_pb'; // proto import: "ai_poi_service.proto"


export class AiPoiServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorHealthCheck = new grpcWeb.MethodDescriptor(
    '/ai_poi.v1.AiPoiService/HealthCheck',
    grpcWeb.MethodType.UNARY,
    common_pb.HealthCheckRequest,
    common_pb.HealthCheckResponse,
    (request: common_pb.HealthCheckRequest) => {
      return request.serializeBinary();
    },
    common_pb.HealthCheckResponse.deserializeBinary
  );

  healthCheck(
    request: common_pb.HealthCheckRequest,
    metadata?: grpcWeb.Metadata | null): Promise<common_pb.HealthCheckResponse>;

  healthCheck(
    request: common_pb.HealthCheckRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: common_pb.HealthCheckResponse) => void): grpcWeb.ClientReadableStream<common_pb.HealthCheckResponse>;

  healthCheck(
    request: common_pb.HealthCheckRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: common_pb.HealthCheckResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.v1.AiPoiService/HealthCheck',
        request,
        metadata || {},
        this.methodDescriptorHealthCheck,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.v1.AiPoiService/HealthCheck',
    request,
    metadata || {},
    this.methodDescriptorHealthCheck);
  }

  methodDescriptorGetServiceInfo = new grpcWeb.MethodDescriptor(
    '/ai_poi.v1.AiPoiService/GetServiceInfo',
    grpcWeb.MethodType.UNARY,
    ai_poi_service_pb.GetServiceInfoRequest,
    ai_poi_service_pb.GetServiceInfoResponse,
    (request: ai_poi_service_pb.GetServiceInfoRequest) => {
      return request.serializeBinary();
    },
    ai_poi_service_pb.GetServiceInfoResponse.deserializeBinary
  );

  getServiceInfo(
    request: ai_poi_service_pb.GetServiceInfoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<ai_poi_service_pb.GetServiceInfoResponse>;

  getServiceInfo(
    request: ai_poi_service_pb.GetServiceInfoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: ai_poi_service_pb.GetServiceInfoResponse) => void): grpcWeb.ClientReadableStream<ai_poi_service_pb.GetServiceInfoResponse>;

  getServiceInfo(
    request: ai_poi_service_pb.GetServiceInfoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: ai_poi_service_pb.GetServiceInfoResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.v1.AiPoiService/GetServiceInfo',
        request,
        metadata || {},
        this.methodDescriptorGetServiceInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.v1.AiPoiService/GetServiceInfo',
    request,
    metadata || {},
    this.methodDescriptorGetServiceInfo);
  }

  methodDescriptorGetFeatureFlags = new grpcWeb.MethodDescriptor(
    '/ai_poi.v1.AiPoiService/GetFeatureFlags',
    grpcWeb.MethodType.UNARY,
    ai_poi_service_pb.GetFeatureFlagsRequest,
    ai_poi_service_pb.GetFeatureFlagsResponse,
    (request: ai_poi_service_pb.GetFeatureFlagsRequest) => {
      return request.serializeBinary();
    },
    ai_poi_service_pb.GetFeatureFlagsResponse.deserializeBinary
  );

  getFeatureFlags(
    request: ai_poi_service_pb.GetFeatureFlagsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<ai_poi_service_pb.GetFeatureFlagsResponse>;

  getFeatureFlags(
    request: ai_poi_service_pb.GetFeatureFlagsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: ai_poi_service_pb.GetFeatureFlagsResponse) => void): grpcWeb.ClientReadableStream<ai_poi_service_pb.GetFeatureFlagsResponse>;

  getFeatureFlags(
    request: ai_poi_service_pb.GetFeatureFlagsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: ai_poi_service_pb.GetFeatureFlagsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.v1.AiPoiService/GetFeatureFlags',
        request,
        metadata || {},
        this.methodDescriptorGetFeatureFlags,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.v1.AiPoiService/GetFeatureFlags',
    request,
    metadata || {},
    this.methodDescriptorGetFeatureFlags);
  }

}

