// source: ai_poi_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.ai_poi.v1.BaseRequest', null, global);
goog.exportSymbol('proto.ai_poi.v1.BaseResponse', null, global);
goog.exportSymbol('proto.ai_poi.v1.GetFeatureFlagsRequest', null, global);
goog.exportSymbol('proto.ai_poi.v1.GetFeatureFlagsResponse', null, global);
goog.exportSymbol('proto.ai_poi.v1.GetServiceInfoRequest', null, global);
goog.exportSymbol('proto.ai_poi.v1.GetServiceInfoResponse', null, global);
goog.exportSymbol('proto.ai_poi.v1.ServiceDependencies', null, global);
goog.exportSymbol('proto.ai_poi.v1.ServiceEndpoint', null, global);
goog.exportSymbol('proto.ai_poi.v1.ServiceInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai_poi.v1.GetServiceInfoRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai_poi.v1.GetServiceInfoRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai_poi.v1.GetServiceInfoRequest.displayName = 'proto.ai_poi.v1.GetServiceInfoRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai_poi.v1.GetServiceInfoResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ai_poi.v1.GetServiceInfoResponse.repeatedFields_, null);
};
goog.inherits(proto.ai_poi.v1.GetServiceInfoResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai_poi.v1.GetServiceInfoResponse.displayName = 'proto.ai_poi.v1.GetServiceInfoResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai_poi.v1.ServiceInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai_poi.v1.ServiceInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai_poi.v1.ServiceInfo.displayName = 'proto.ai_poi.v1.ServiceInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai_poi.v1.ServiceEndpoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ai_poi.v1.ServiceEndpoint.repeatedFields_, null);
};
goog.inherits(proto.ai_poi.v1.ServiceEndpoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai_poi.v1.ServiceEndpoint.displayName = 'proto.ai_poi.v1.ServiceEndpoint';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai_poi.v1.GetFeatureFlagsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai_poi.v1.GetFeatureFlagsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai_poi.v1.GetFeatureFlagsRequest.displayName = 'proto.ai_poi.v1.GetFeatureFlagsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai_poi.v1.GetFeatureFlagsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ai_poi.v1.GetFeatureFlagsResponse.repeatedFields_, null);
};
goog.inherits(proto.ai_poi.v1.GetFeatureFlagsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai_poi.v1.GetFeatureFlagsResponse.displayName = 'proto.ai_poi.v1.GetFeatureFlagsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai_poi.v1.ServiceDependencies = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai_poi.v1.ServiceDependencies, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai_poi.v1.ServiceDependencies.displayName = 'proto.ai_poi.v1.ServiceDependencies';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai_poi.v1.BaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.ai_poi.v1.BaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai_poi.v1.BaseRequest.displayName = 'proto.ai_poi.v1.BaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai_poi.v1.BaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.ai_poi.v1.BaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai_poi.v1.BaseResponse.displayName = 'proto.ai_poi.v1.BaseResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai_poi.v1.GetServiceInfoRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai_poi.v1.GetServiceInfoRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai_poi.v1.GetServiceInfoRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.GetServiceInfoRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
includeEndpoints: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
includeVersionInfo: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
request: (f = msg.getRequest()) && proto.ai_poi.v1.BaseRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai_poi.v1.GetServiceInfoRequest}
 */
proto.ai_poi.v1.GetServiceInfoRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai_poi.v1.GetServiceInfoRequest;
  return proto.ai_poi.v1.GetServiceInfoRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai_poi.v1.GetServiceInfoRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai_poi.v1.GetServiceInfoRequest}
 */
proto.ai_poi.v1.GetServiceInfoRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeEndpoints(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeVersionInfo(value);
      break;
    case 100:
      var value = new proto.ai_poi.v1.BaseRequest;
      reader.readMessage(value,proto.ai_poi.v1.BaseRequest.deserializeBinaryFromReader);
      msg.setRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai_poi.v1.GetServiceInfoRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai_poi.v1.GetServiceInfoRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai_poi.v1.GetServiceInfoRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.GetServiceInfoRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIncludeEndpoints();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getIncludeVersionInfo();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getRequest();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      proto.ai_poi.v1.BaseRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool include_endpoints = 1;
 * @return {boolean}
 */
proto.ai_poi.v1.GetServiceInfoRequest.prototype.getIncludeEndpoints = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ai_poi.v1.GetServiceInfoRequest} returns this
 */
proto.ai_poi.v1.GetServiceInfoRequest.prototype.setIncludeEndpoints = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool include_version_info = 2;
 * @return {boolean}
 */
proto.ai_poi.v1.GetServiceInfoRequest.prototype.getIncludeVersionInfo = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ai_poi.v1.GetServiceInfoRequest} returns this
 */
proto.ai_poi.v1.GetServiceInfoRequest.prototype.setIncludeVersionInfo = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional BaseRequest request = 100;
 * @return {?proto.ai_poi.v1.BaseRequest}
 */
proto.ai_poi.v1.GetServiceInfoRequest.prototype.getRequest = function() {
  return /** @type{?proto.ai_poi.v1.BaseRequest} */ (
    jspb.Message.getWrapperField(this, proto.ai_poi.v1.BaseRequest, 100));
};


/**
 * @param {?proto.ai_poi.v1.BaseRequest|undefined} value
 * @return {!proto.ai_poi.v1.GetServiceInfoRequest} returns this
*/
proto.ai_poi.v1.GetServiceInfoRequest.prototype.setRequest = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai_poi.v1.GetServiceInfoRequest} returns this
 */
proto.ai_poi.v1.GetServiceInfoRequest.prototype.clearRequest = function() {
  return this.setRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai_poi.v1.GetServiceInfoRequest.prototype.hasRequest = function() {
  return jspb.Message.getField(this, 100) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ai_poi.v1.GetServiceInfoResponse.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ai_poi.v1.GetServiceInfoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai_poi.v1.GetServiceInfoResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.GetServiceInfoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
serviceInfo: (f = msg.getServiceInfo()) && proto.ai_poi.v1.ServiceInfo.toObject(includeInstance, f),
endpointsList: jspb.Message.toObjectList(msg.getEndpointsList(),
    proto.ai_poi.v1.ServiceEndpoint.toObject, includeInstance),
versionsList: jspb.Message.toObjectList(msg.getVersionsList(),
    common_pb.ApiVersion.toObject, includeInstance),
response: (f = msg.getResponse()) && proto.ai_poi.v1.BaseResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai_poi.v1.GetServiceInfoResponse}
 */
proto.ai_poi.v1.GetServiceInfoResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai_poi.v1.GetServiceInfoResponse;
  return proto.ai_poi.v1.GetServiceInfoResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai_poi.v1.GetServiceInfoResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai_poi.v1.GetServiceInfoResponse}
 */
proto.ai_poi.v1.GetServiceInfoResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ai_poi.v1.ServiceInfo;
      reader.readMessage(value,proto.ai_poi.v1.ServiceInfo.deserializeBinaryFromReader);
      msg.setServiceInfo(value);
      break;
    case 2:
      var value = new proto.ai_poi.v1.ServiceEndpoint;
      reader.readMessage(value,proto.ai_poi.v1.ServiceEndpoint.deserializeBinaryFromReader);
      msg.addEndpoints(value);
      break;
    case 3:
      var value = new common_pb.ApiVersion;
      reader.readMessage(value,common_pb.ApiVersion.deserializeBinaryFromReader);
      msg.addVersions(value);
      break;
    case 100:
      var value = new proto.ai_poi.v1.BaseResponse;
      reader.readMessage(value,proto.ai_poi.v1.BaseResponse.deserializeBinaryFromReader);
      msg.setResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai_poi.v1.GetServiceInfoResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai_poi.v1.GetServiceInfoResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.GetServiceInfoResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServiceInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ai_poi.v1.ServiceInfo.serializeBinaryToWriter
    );
  }
  f = message.getEndpointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.ai_poi.v1.ServiceEndpoint.serializeBinaryToWriter
    );
  }
  f = message.getVersionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      common_pb.ApiVersion.serializeBinaryToWriter
    );
  }
  f = message.getResponse();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      proto.ai_poi.v1.BaseResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServiceInfo service_info = 1;
 * @return {?proto.ai_poi.v1.ServiceInfo}
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.getServiceInfo = function() {
  return /** @type{?proto.ai_poi.v1.ServiceInfo} */ (
    jspb.Message.getWrapperField(this, proto.ai_poi.v1.ServiceInfo, 1));
};


/**
 * @param {?proto.ai_poi.v1.ServiceInfo|undefined} value
 * @return {!proto.ai_poi.v1.GetServiceInfoResponse} returns this
*/
proto.ai_poi.v1.GetServiceInfoResponse.prototype.setServiceInfo = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai_poi.v1.GetServiceInfoResponse} returns this
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.clearServiceInfo = function() {
  return this.setServiceInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.hasServiceInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated ServiceEndpoint endpoints = 2;
 * @return {!Array<!proto.ai_poi.v1.ServiceEndpoint>}
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.getEndpointsList = function() {
  return /** @type{!Array<!proto.ai_poi.v1.ServiceEndpoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ai_poi.v1.ServiceEndpoint, 2));
};


/**
 * @param {!Array<!proto.ai_poi.v1.ServiceEndpoint>} value
 * @return {!proto.ai_poi.v1.GetServiceInfoResponse} returns this
*/
proto.ai_poi.v1.GetServiceInfoResponse.prototype.setEndpointsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ai_poi.v1.ServiceEndpoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ai_poi.v1.ServiceEndpoint}
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.addEndpoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ai_poi.v1.ServiceEndpoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ai_poi.v1.GetServiceInfoResponse} returns this
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.clearEndpointsList = function() {
  return this.setEndpointsList([]);
};


/**
 * repeated ai_poi.common.v1.ApiVersion versions = 3;
 * @return {!Array<!proto.ai_poi.common.v1.ApiVersion>}
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.getVersionsList = function() {
  return /** @type{!Array<!proto.ai_poi.common.v1.ApiVersion>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_pb.ApiVersion, 3));
};


/**
 * @param {!Array<!proto.ai_poi.common.v1.ApiVersion>} value
 * @return {!proto.ai_poi.v1.GetServiceInfoResponse} returns this
*/
proto.ai_poi.v1.GetServiceInfoResponse.prototype.setVersionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.ai_poi.common.v1.ApiVersion=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ai_poi.common.v1.ApiVersion}
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.addVersions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.ai_poi.common.v1.ApiVersion, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ai_poi.v1.GetServiceInfoResponse} returns this
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.clearVersionsList = function() {
  return this.setVersionsList([]);
};


/**
 * optional BaseResponse response = 100;
 * @return {?proto.ai_poi.v1.BaseResponse}
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.getResponse = function() {
  return /** @type{?proto.ai_poi.v1.BaseResponse} */ (
    jspb.Message.getWrapperField(this, proto.ai_poi.v1.BaseResponse, 100));
};


/**
 * @param {?proto.ai_poi.v1.BaseResponse|undefined} value
 * @return {!proto.ai_poi.v1.GetServiceInfoResponse} returns this
*/
proto.ai_poi.v1.GetServiceInfoResponse.prototype.setResponse = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai_poi.v1.GetServiceInfoResponse} returns this
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.clearResponse = function() {
  return this.setResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai_poi.v1.GetServiceInfoResponse.prototype.hasResponse = function() {
  return jspb.Message.getField(this, 100) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai_poi.v1.ServiceInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.ai_poi.v1.ServiceInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai_poi.v1.ServiceInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.ServiceInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
name: jspb.Message.getFieldWithDefault(msg, 1, ""),
version: jspb.Message.getFieldWithDefault(msg, 2, ""),
description: jspb.Message.getFieldWithDefault(msg, 3, ""),
buildTime: jspb.Message.getFieldWithDefault(msg, 4, ""),
gitCommit: jspb.Message.getFieldWithDefault(msg, 5, ""),
environment: jspb.Message.getFieldWithDefault(msg, 6, ""),
configurationMap: (f = msg.getConfigurationMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai_poi.v1.ServiceInfo}
 */
proto.ai_poi.v1.ServiceInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai_poi.v1.ServiceInfo;
  return proto.ai_poi.v1.ServiceInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai_poi.v1.ServiceInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai_poi.v1.ServiceInfo}
 */
proto.ai_poi.v1.ServiceInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBuildTime(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setGitCommit(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setEnvironment(value);
      break;
    case 7:
      var value = msg.getConfigurationMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai_poi.v1.ServiceInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai_poi.v1.ServiceInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai_poi.v1.ServiceInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.ServiceInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBuildTime();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getGitCommit();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getEnvironment();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getConfigurationMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.ai_poi.v1.ServiceInfo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.ServiceInfo} returns this
 */
proto.ai_poi.v1.ServiceInfo.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string version = 2;
 * @return {string}
 */
proto.ai_poi.v1.ServiceInfo.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.ServiceInfo} returns this
 */
proto.ai_poi.v1.ServiceInfo.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.ai_poi.v1.ServiceInfo.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.ServiceInfo} returns this
 */
proto.ai_poi.v1.ServiceInfo.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string build_time = 4;
 * @return {string}
 */
proto.ai_poi.v1.ServiceInfo.prototype.getBuildTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.ServiceInfo} returns this
 */
proto.ai_poi.v1.ServiceInfo.prototype.setBuildTime = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string git_commit = 5;
 * @return {string}
 */
proto.ai_poi.v1.ServiceInfo.prototype.getGitCommit = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.ServiceInfo} returns this
 */
proto.ai_poi.v1.ServiceInfo.prototype.setGitCommit = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string environment = 6;
 * @return {string}
 */
proto.ai_poi.v1.ServiceInfo.prototype.getEnvironment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.ServiceInfo} returns this
 */
proto.ai_poi.v1.ServiceInfo.prototype.setEnvironment = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * map<string, string> configuration = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.ai_poi.v1.ServiceInfo.prototype.getConfigurationMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.ai_poi.v1.ServiceInfo} returns this
 */
proto.ai_poi.v1.ServiceInfo.prototype.clearConfigurationMap = function() {
  this.getConfigurationMap().clear();
  return this;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ai_poi.v1.ServiceEndpoint.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.toObject = function(opt_includeInstance) {
  return proto.ai_poi.v1.ServiceEndpoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai_poi.v1.ServiceEndpoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.ServiceEndpoint.toObject = function(includeInstance, msg) {
  var f, obj = {
name: jspb.Message.getFieldWithDefault(msg, 1, ""),
path: jspb.Message.getFieldWithDefault(msg, 2, ""),
method: jspb.Message.getFieldWithDefault(msg, 3, ""),
description: jspb.Message.getFieldWithDefault(msg, 4, ""),
requiresAuth: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
requiredPermissionsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
rateLimit: (f = msg.getRateLimit()) && common_pb.RateLimitInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai_poi.v1.ServiceEndpoint}
 */
proto.ai_poi.v1.ServiceEndpoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai_poi.v1.ServiceEndpoint;
  return proto.ai_poi.v1.ServiceEndpoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai_poi.v1.ServiceEndpoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai_poi.v1.ServiceEndpoint}
 */
proto.ai_poi.v1.ServiceEndpoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMethod(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRequiresAuth(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addRequiredPermissions(value);
      break;
    case 7:
      var value = new common_pb.RateLimitInfo;
      reader.readMessage(value,common_pb.RateLimitInfo.deserializeBinaryFromReader);
      msg.setRateLimit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai_poi.v1.ServiceEndpoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai_poi.v1.ServiceEndpoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.ServiceEndpoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMethod();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRequiresAuth();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getRequiredPermissionsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
  f = message.getRateLimit();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      common_pb.RateLimitInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.ServiceEndpoint} returns this
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string path = 2;
 * @return {string}
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.ServiceEndpoint} returns this
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string method = 3;
 * @return {string}
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.getMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.ServiceEndpoint} returns this
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.setMethod = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.ServiceEndpoint} returns this
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool requires_auth = 5;
 * @return {boolean}
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.getRequiresAuth = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ai_poi.v1.ServiceEndpoint} returns this
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.setRequiresAuth = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * repeated string required_permissions = 6;
 * @return {!Array<string>}
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.getRequiredPermissionsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.ai_poi.v1.ServiceEndpoint} returns this
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.setRequiredPermissionsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.ai_poi.v1.ServiceEndpoint} returns this
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.addRequiredPermissions = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ai_poi.v1.ServiceEndpoint} returns this
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.clearRequiredPermissionsList = function() {
  return this.setRequiredPermissionsList([]);
};


/**
 * optional ai_poi.common.v1.RateLimitInfo rate_limit = 7;
 * @return {?proto.ai_poi.common.v1.RateLimitInfo}
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.getRateLimit = function() {
  return /** @type{?proto.ai_poi.common.v1.RateLimitInfo} */ (
    jspb.Message.getWrapperField(this, common_pb.RateLimitInfo, 7));
};


/**
 * @param {?proto.ai_poi.common.v1.RateLimitInfo|undefined} value
 * @return {!proto.ai_poi.v1.ServiceEndpoint} returns this
*/
proto.ai_poi.v1.ServiceEndpoint.prototype.setRateLimit = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai_poi.v1.ServiceEndpoint} returns this
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.clearRateLimit = function() {
  return this.setRateLimit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai_poi.v1.ServiceEndpoint.prototype.hasRateLimit = function() {
  return jspb.Message.getField(this, 7) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai_poi.v1.GetFeatureFlagsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai_poi.v1.GetFeatureFlagsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
clientVersion: jspb.Message.getFieldWithDefault(msg, 2, ""),
platform: jspb.Message.getFieldWithDefault(msg, 3, ""),
userAttributesMap: (f = msg.getUserAttributesMap()) ? f.toObject(includeInstance, undefined) : [],
request: (f = msg.getRequest()) && proto.ai_poi.v1.BaseRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai_poi.v1.GetFeatureFlagsRequest}
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai_poi.v1.GetFeatureFlagsRequest;
  return proto.ai_poi.v1.GetFeatureFlagsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai_poi.v1.GetFeatureFlagsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai_poi.v1.GetFeatureFlagsRequest}
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatform(value);
      break;
    case 4:
      var value = msg.getUserAttributesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 100:
      var value = new proto.ai_poi.v1.BaseRequest;
      reader.readMessage(value,proto.ai_poi.v1.BaseRequest.deserializeBinaryFromReader);
      msg.setRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai_poi.v1.GetFeatureFlagsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai_poi.v1.GetFeatureFlagsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getClientVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPlatform();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUserAttributesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getRequest();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      proto.ai_poi.v1.BaseRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.GetFeatureFlagsRequest} returns this
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string client_version = 2;
 * @return {string}
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.getClientVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.GetFeatureFlagsRequest} returns this
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.setClientVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string platform = 3;
 * @return {string}
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.getPlatform = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.GetFeatureFlagsRequest} returns this
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.setPlatform = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * map<string, string> user_attributes = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.getUserAttributesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.ai_poi.v1.GetFeatureFlagsRequest} returns this
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.clearUserAttributesMap = function() {
  this.getUserAttributesMap().clear();
  return this;
};


/**
 * optional BaseRequest request = 100;
 * @return {?proto.ai_poi.v1.BaseRequest}
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.getRequest = function() {
  return /** @type{?proto.ai_poi.v1.BaseRequest} */ (
    jspb.Message.getWrapperField(this, proto.ai_poi.v1.BaseRequest, 100));
};


/**
 * @param {?proto.ai_poi.v1.BaseRequest|undefined} value
 * @return {!proto.ai_poi.v1.GetFeatureFlagsRequest} returns this
*/
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.setRequest = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai_poi.v1.GetFeatureFlagsRequest} returns this
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.clearRequest = function() {
  return this.setRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai_poi.v1.GetFeatureFlagsRequest.prototype.hasRequest = function() {
  return jspb.Message.getField(this, 100) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ai_poi.v1.GetFeatureFlagsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai_poi.v1.GetFeatureFlagsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
flagsList: jspb.Message.toObjectList(msg.getFlagsList(),
    common_pb.FeatureFlag.toObject, includeInstance),
experimentsMap: (f = msg.getExperimentsMap()) ? f.toObject(includeInstance, undefined) : [],
response: (f = msg.getResponse()) && proto.ai_poi.v1.BaseResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai_poi.v1.GetFeatureFlagsResponse}
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai_poi.v1.GetFeatureFlagsResponse;
  return proto.ai_poi.v1.GetFeatureFlagsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai_poi.v1.GetFeatureFlagsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai_poi.v1.GetFeatureFlagsResponse}
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.FeatureFlag;
      reader.readMessage(value,common_pb.FeatureFlag.deserializeBinaryFromReader);
      msg.addFlags(value);
      break;
    case 2:
      var value = msg.getExperimentsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 100:
      var value = new proto.ai_poi.v1.BaseResponse;
      reader.readMessage(value,proto.ai_poi.v1.BaseResponse.deserializeBinaryFromReader);
      msg.setResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai_poi.v1.GetFeatureFlagsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai_poi.v1.GetFeatureFlagsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFlagsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      common_pb.FeatureFlag.serializeBinaryToWriter
    );
  }
  f = message.getExperimentsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getResponse();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      proto.ai_poi.v1.BaseResponse.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ai_poi.common.v1.FeatureFlag flags = 1;
 * @return {!Array<!proto.ai_poi.common.v1.FeatureFlag>}
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.prototype.getFlagsList = function() {
  return /** @type{!Array<!proto.ai_poi.common.v1.FeatureFlag>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_pb.FeatureFlag, 1));
};


/**
 * @param {!Array<!proto.ai_poi.common.v1.FeatureFlag>} value
 * @return {!proto.ai_poi.v1.GetFeatureFlagsResponse} returns this
*/
proto.ai_poi.v1.GetFeatureFlagsResponse.prototype.setFlagsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.ai_poi.common.v1.FeatureFlag=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ai_poi.common.v1.FeatureFlag}
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.prototype.addFlags = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.ai_poi.common.v1.FeatureFlag, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ai_poi.v1.GetFeatureFlagsResponse} returns this
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.prototype.clearFlagsList = function() {
  return this.setFlagsList([]);
};


/**
 * map<string, string> experiments = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.prototype.getExperimentsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.ai_poi.v1.GetFeatureFlagsResponse} returns this
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.prototype.clearExperimentsMap = function() {
  this.getExperimentsMap().clear();
  return this;
};


/**
 * optional BaseResponse response = 100;
 * @return {?proto.ai_poi.v1.BaseResponse}
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.prototype.getResponse = function() {
  return /** @type{?proto.ai_poi.v1.BaseResponse} */ (
    jspb.Message.getWrapperField(this, proto.ai_poi.v1.BaseResponse, 100));
};


/**
 * @param {?proto.ai_poi.v1.BaseResponse|undefined} value
 * @return {!proto.ai_poi.v1.GetFeatureFlagsResponse} returns this
*/
proto.ai_poi.v1.GetFeatureFlagsResponse.prototype.setResponse = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai_poi.v1.GetFeatureFlagsResponse} returns this
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.prototype.clearResponse = function() {
  return this.setResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai_poi.v1.GetFeatureFlagsResponse.prototype.hasResponse = function() {
  return jspb.Message.getField(this, 100) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai_poi.v1.ServiceDependencies.prototype.toObject = function(opt_includeInstance) {
  return proto.ai_poi.v1.ServiceDependencies.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai_poi.v1.ServiceDependencies} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.ServiceDependencies.toObject = function(includeInstance, msg) {
  var f, obj = {
database: (f = msg.getDatabase()) && common_pb.ComponentHealth.toObject(includeInstance, f),
redisCache: (f = msg.getRedisCache()) && common_pb.ComponentHealth.toObject(includeInstance, f),
aiService: (f = msg.getAiService()) && common_pb.ComponentHealth.toObject(includeInstance, f),
externalApis: (f = msg.getExternalApis()) && common_pb.ComponentHealth.toObject(includeInstance, f),
fileStorage: (f = msg.getFileStorage()) && common_pb.ComponentHealth.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai_poi.v1.ServiceDependencies}
 */
proto.ai_poi.v1.ServiceDependencies.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai_poi.v1.ServiceDependencies;
  return proto.ai_poi.v1.ServiceDependencies.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai_poi.v1.ServiceDependencies} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai_poi.v1.ServiceDependencies}
 */
proto.ai_poi.v1.ServiceDependencies.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.ComponentHealth;
      reader.readMessage(value,common_pb.ComponentHealth.deserializeBinaryFromReader);
      msg.setDatabase(value);
      break;
    case 2:
      var value = new common_pb.ComponentHealth;
      reader.readMessage(value,common_pb.ComponentHealth.deserializeBinaryFromReader);
      msg.setRedisCache(value);
      break;
    case 3:
      var value = new common_pb.ComponentHealth;
      reader.readMessage(value,common_pb.ComponentHealth.deserializeBinaryFromReader);
      msg.setAiService(value);
      break;
    case 4:
      var value = new common_pb.ComponentHealth;
      reader.readMessage(value,common_pb.ComponentHealth.deserializeBinaryFromReader);
      msg.setExternalApis(value);
      break;
    case 5:
      var value = new common_pb.ComponentHealth;
      reader.readMessage(value,common_pb.ComponentHealth.deserializeBinaryFromReader);
      msg.setFileStorage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai_poi.v1.ServiceDependencies.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai_poi.v1.ServiceDependencies.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai_poi.v1.ServiceDependencies} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.ServiceDependencies.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDatabase();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.ComponentHealth.serializeBinaryToWriter
    );
  }
  f = message.getRedisCache();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_pb.ComponentHealth.serializeBinaryToWriter
    );
  }
  f = message.getAiService();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      common_pb.ComponentHealth.serializeBinaryToWriter
    );
  }
  f = message.getExternalApis();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      common_pb.ComponentHealth.serializeBinaryToWriter
    );
  }
  f = message.getFileStorage();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      common_pb.ComponentHealth.serializeBinaryToWriter
    );
  }
};


/**
 * optional ai_poi.common.v1.ComponentHealth database = 1;
 * @return {?proto.ai_poi.common.v1.ComponentHealth}
 */
proto.ai_poi.v1.ServiceDependencies.prototype.getDatabase = function() {
  return /** @type{?proto.ai_poi.common.v1.ComponentHealth} */ (
    jspb.Message.getWrapperField(this, common_pb.ComponentHealth, 1));
};


/**
 * @param {?proto.ai_poi.common.v1.ComponentHealth|undefined} value
 * @return {!proto.ai_poi.v1.ServiceDependencies} returns this
*/
proto.ai_poi.v1.ServiceDependencies.prototype.setDatabase = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai_poi.v1.ServiceDependencies} returns this
 */
proto.ai_poi.v1.ServiceDependencies.prototype.clearDatabase = function() {
  return this.setDatabase(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai_poi.v1.ServiceDependencies.prototype.hasDatabase = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ai_poi.common.v1.ComponentHealth redis_cache = 2;
 * @return {?proto.ai_poi.common.v1.ComponentHealth}
 */
proto.ai_poi.v1.ServiceDependencies.prototype.getRedisCache = function() {
  return /** @type{?proto.ai_poi.common.v1.ComponentHealth} */ (
    jspb.Message.getWrapperField(this, common_pb.ComponentHealth, 2));
};


/**
 * @param {?proto.ai_poi.common.v1.ComponentHealth|undefined} value
 * @return {!proto.ai_poi.v1.ServiceDependencies} returns this
*/
proto.ai_poi.v1.ServiceDependencies.prototype.setRedisCache = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai_poi.v1.ServiceDependencies} returns this
 */
proto.ai_poi.v1.ServiceDependencies.prototype.clearRedisCache = function() {
  return this.setRedisCache(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai_poi.v1.ServiceDependencies.prototype.hasRedisCache = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ai_poi.common.v1.ComponentHealth ai_service = 3;
 * @return {?proto.ai_poi.common.v1.ComponentHealth}
 */
proto.ai_poi.v1.ServiceDependencies.prototype.getAiService = function() {
  return /** @type{?proto.ai_poi.common.v1.ComponentHealth} */ (
    jspb.Message.getWrapperField(this, common_pb.ComponentHealth, 3));
};


/**
 * @param {?proto.ai_poi.common.v1.ComponentHealth|undefined} value
 * @return {!proto.ai_poi.v1.ServiceDependencies} returns this
*/
proto.ai_poi.v1.ServiceDependencies.prototype.setAiService = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai_poi.v1.ServiceDependencies} returns this
 */
proto.ai_poi.v1.ServiceDependencies.prototype.clearAiService = function() {
  return this.setAiService(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai_poi.v1.ServiceDependencies.prototype.hasAiService = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ai_poi.common.v1.ComponentHealth external_apis = 4;
 * @return {?proto.ai_poi.common.v1.ComponentHealth}
 */
proto.ai_poi.v1.ServiceDependencies.prototype.getExternalApis = function() {
  return /** @type{?proto.ai_poi.common.v1.ComponentHealth} */ (
    jspb.Message.getWrapperField(this, common_pb.ComponentHealth, 4));
};


/**
 * @param {?proto.ai_poi.common.v1.ComponentHealth|undefined} value
 * @return {!proto.ai_poi.v1.ServiceDependencies} returns this
*/
proto.ai_poi.v1.ServiceDependencies.prototype.setExternalApis = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai_poi.v1.ServiceDependencies} returns this
 */
proto.ai_poi.v1.ServiceDependencies.prototype.clearExternalApis = function() {
  return this.setExternalApis(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai_poi.v1.ServiceDependencies.prototype.hasExternalApis = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ai_poi.common.v1.ComponentHealth file_storage = 5;
 * @return {?proto.ai_poi.common.v1.ComponentHealth}
 */
proto.ai_poi.v1.ServiceDependencies.prototype.getFileStorage = function() {
  return /** @type{?proto.ai_poi.common.v1.ComponentHealth} */ (
    jspb.Message.getWrapperField(this, common_pb.ComponentHealth, 5));
};


/**
 * @param {?proto.ai_poi.common.v1.ComponentHealth|undefined} value
 * @return {!proto.ai_poi.v1.ServiceDependencies} returns this
*/
proto.ai_poi.v1.ServiceDependencies.prototype.setFileStorage = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai_poi.v1.ServiceDependencies} returns this
 */
proto.ai_poi.v1.ServiceDependencies.prototype.clearFileStorage = function() {
  return this.setFileStorage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai_poi.v1.ServiceDependencies.prototype.hasFileStorage = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai_poi.v1.BaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai_poi.v1.BaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai_poi.v1.BaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.BaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
downstream: jspb.Message.getFieldWithDefault(msg, 998, ""),
requestId: jspb.Message.getFieldWithDefault(msg, 999, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai_poi.v1.BaseRequest}
 */
proto.ai_poi.v1.BaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai_poi.v1.BaseRequest;
  return proto.ai_poi.v1.BaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai_poi.v1.BaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai_poi.v1.BaseRequest}
 */
proto.ai_poi.v1.BaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 998:
      var value = /** @type {string} */ (reader.readString());
      msg.setDownstream(value);
      break;
    case 999:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai_poi.v1.BaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai_poi.v1.BaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai_poi.v1.BaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.BaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDownstream();
  if (f.length > 0) {
    writer.writeString(
      998,
      f
    );
  }
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      999,
      f
    );
  }
};


/**
 * optional string downstream = 998;
 * @return {string}
 */
proto.ai_poi.v1.BaseRequest.prototype.getDownstream = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 998, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.BaseRequest} returns this
 */
proto.ai_poi.v1.BaseRequest.prototype.setDownstream = function(value) {
  return jspb.Message.setProto3StringField(this, 998, value);
};


/**
 * optional string request_id = 999;
 * @return {string}
 */
proto.ai_poi.v1.BaseRequest.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 999, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.BaseRequest} returns this
 */
proto.ai_poi.v1.BaseRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 999, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai_poi.v1.BaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ai_poi.v1.BaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai_poi.v1.BaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.BaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
upstream: jspb.Message.getFieldWithDefault(msg, 998, ""),
requestId: jspb.Message.getFieldWithDefault(msg, 999, ""),
status: jspb.Message.getFieldWithDefault(msg, 1000, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai_poi.v1.BaseResponse}
 */
proto.ai_poi.v1.BaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai_poi.v1.BaseResponse;
  return proto.ai_poi.v1.BaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai_poi.v1.BaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai_poi.v1.BaseResponse}
 */
proto.ai_poi.v1.BaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 998:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpstream(value);
      break;
    case 999:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestId(value);
      break;
    case 1000:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai_poi.v1.BaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai_poi.v1.BaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai_poi.v1.BaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai_poi.v1.BaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUpstream();
  if (f.length > 0) {
    writer.writeString(
      998,
      f
    );
  }
  f = message.getRequestId();
  if (f.length > 0) {
    writer.writeString(
      999,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      1000,
      f
    );
  }
};


/**
 * optional string upstream = 998;
 * @return {string}
 */
proto.ai_poi.v1.BaseResponse.prototype.getUpstream = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 998, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.BaseResponse} returns this
 */
proto.ai_poi.v1.BaseResponse.prototype.setUpstream = function(value) {
  return jspb.Message.setProto3StringField(this, 998, value);
};


/**
 * optional string request_id = 999;
 * @return {string}
 */
proto.ai_poi.v1.BaseResponse.prototype.getRequestId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 999, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.BaseResponse} returns this
 */
proto.ai_poi.v1.BaseResponse.prototype.setRequestId = function(value) {
  return jspb.Message.setProto3StringField(this, 999, value);
};


/**
 * optional string status = 1000;
 * @return {string}
 */
proto.ai_poi.v1.BaseResponse.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1000, ""));
};


/**
 * @param {string} value
 * @return {!proto.ai_poi.v1.BaseResponse} returns this
 */
proto.ai_poi.v1.BaseResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 1000, value);
};


goog.object.extend(exports, proto.ai_poi.v1);
