/**
 * @fileoverview gRPC-Web generated client stub for ai_poi.interests.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: interests.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.ai_poi = {};
proto.ai_poi.interests = {};
proto.ai_poi.interests.v1 = require('./interests_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai_poi.interests.v1.InterestsServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai_poi.interests.v1.InterestsServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.interests.v1.GetAllInterestsRequest,
 *   !proto.ai_poi.interests.v1.GetAllInterestsResponse>}
 */
const methodDescriptor_InterestsService_GetAllInterests = new grpc.web.MethodDescriptor(
  '/ai_poi.interests.v1.InterestsService/GetAllInterests',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.interests.v1.GetAllInterestsRequest,
  proto.ai_poi.interests.v1.GetAllInterestsResponse,
  /**
   * @param {!proto.ai_poi.interests.v1.GetAllInterestsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.interests.v1.GetAllInterestsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.interests.v1.GetAllInterestsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.interests.v1.GetAllInterestsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.interests.v1.GetAllInterestsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.interests.v1.InterestsServiceClient.prototype.getAllInterests =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.interests.v1.InterestsService/GetAllInterests',
      request,
      metadata || {},
      methodDescriptor_InterestsService_GetAllInterests,
      callback);
};


/**
 * @param {!proto.ai_poi.interests.v1.GetAllInterestsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.interests.v1.GetAllInterestsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.interests.v1.InterestsServicePromiseClient.prototype.getAllInterests =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.interests.v1.InterestsService/GetAllInterests',
      request,
      metadata || {},
      methodDescriptor_InterestsService_GetAllInterests);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.interests.v1.CreateInterestRequest,
 *   !proto.ai_poi.interests.v1.CreateInterestResponse>}
 */
const methodDescriptor_InterestsService_CreateInterest = new grpc.web.MethodDescriptor(
  '/ai_poi.interests.v1.InterestsService/CreateInterest',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.interests.v1.CreateInterestRequest,
  proto.ai_poi.interests.v1.CreateInterestResponse,
  /**
   * @param {!proto.ai_poi.interests.v1.CreateInterestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.interests.v1.CreateInterestResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.interests.v1.CreateInterestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.interests.v1.CreateInterestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.interests.v1.CreateInterestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.interests.v1.InterestsServiceClient.prototype.createInterest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.interests.v1.InterestsService/CreateInterest',
      request,
      metadata || {},
      methodDescriptor_InterestsService_CreateInterest,
      callback);
};


/**
 * @param {!proto.ai_poi.interests.v1.CreateInterestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.interests.v1.CreateInterestResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.interests.v1.InterestsServicePromiseClient.prototype.createInterest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.interests.v1.InterestsService/CreateInterest',
      request,
      metadata || {},
      methodDescriptor_InterestsService_CreateInterest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.interests.v1.UpdateInterestRequest,
 *   !proto.ai_poi.interests.v1.UpdateInterestResponse>}
 */
const methodDescriptor_InterestsService_UpdateInterest = new grpc.web.MethodDescriptor(
  '/ai_poi.interests.v1.InterestsService/UpdateInterest',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.interests.v1.UpdateInterestRequest,
  proto.ai_poi.interests.v1.UpdateInterestResponse,
  /**
   * @param {!proto.ai_poi.interests.v1.UpdateInterestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.interests.v1.UpdateInterestResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.interests.v1.UpdateInterestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.interests.v1.UpdateInterestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.interests.v1.UpdateInterestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.interests.v1.InterestsServiceClient.prototype.updateInterest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.interests.v1.InterestsService/UpdateInterest',
      request,
      metadata || {},
      methodDescriptor_InterestsService_UpdateInterest,
      callback);
};


/**
 * @param {!proto.ai_poi.interests.v1.UpdateInterestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.interests.v1.UpdateInterestResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.interests.v1.InterestsServicePromiseClient.prototype.updateInterest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.interests.v1.InterestsService/UpdateInterest',
      request,
      metadata || {},
      methodDescriptor_InterestsService_UpdateInterest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.interests.v1.RemoveInterestRequest,
 *   !proto.ai_poi.interests.v1.RemoveInterestResponse>}
 */
const methodDescriptor_InterestsService_RemoveInterest = new grpc.web.MethodDescriptor(
  '/ai_poi.interests.v1.InterestsService/RemoveInterest',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.interests.v1.RemoveInterestRequest,
  proto.ai_poi.interests.v1.RemoveInterestResponse,
  /**
   * @param {!proto.ai_poi.interests.v1.RemoveInterestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.interests.v1.RemoveInterestResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.interests.v1.RemoveInterestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.interests.v1.RemoveInterestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.interests.v1.RemoveInterestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.interests.v1.InterestsServiceClient.prototype.removeInterest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.interests.v1.InterestsService/RemoveInterest',
      request,
      metadata || {},
      methodDescriptor_InterestsService_RemoveInterest,
      callback);
};


/**
 * @param {!proto.ai_poi.interests.v1.RemoveInterestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.interests.v1.RemoveInterestResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.interests.v1.InterestsServicePromiseClient.prototype.removeInterest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.interests.v1.InterestsService/RemoveInterest',
      request,
      metadata || {},
      methodDescriptor_InterestsService_RemoveInterest);
};


module.exports = proto.ai_poi.interests.v1;

