/**
 * @fileoverview gRPC-Web generated client stub for ai_poi.list.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: list.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.ai_poi = {};
proto.ai_poi.list = {};
proto.ai_poi.list.v1 = require('./list_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai_poi.list.v1.ListServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai_poi.list.v1.ListServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.CreateListRequest,
 *   !proto.ai_poi.list.v1.CreateListResponse>}
 */
const methodDescriptor_ListService_CreateList = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/CreateList',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.CreateListRequest,
  proto.ai_poi.list.v1.CreateListResponse,
  /**
   * @param {!proto.ai_poi.list.v1.CreateListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.CreateListResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.CreateListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.CreateListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.CreateListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.createList =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/CreateList',
      request,
      metadata || {},
      methodDescriptor_ListService_CreateList,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.CreateListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.CreateListResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.createList =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/CreateList',
      request,
      metadata || {},
      methodDescriptor_ListService_CreateList);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.GetListsRequest,
 *   !proto.ai_poi.list.v1.GetListsResponse>}
 */
const methodDescriptor_ListService_GetLists = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/GetLists',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.GetListsRequest,
  proto.ai_poi.list.v1.GetListsResponse,
  /**
   * @param {!proto.ai_poi.list.v1.GetListsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.GetListsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.GetListsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.GetListsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.GetListsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.getLists =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetLists',
      request,
      metadata || {},
      methodDescriptor_ListService_GetLists,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.GetListsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.GetListsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.getLists =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetLists',
      request,
      metadata || {},
      methodDescriptor_ListService_GetLists);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.GetListRequest,
 *   !proto.ai_poi.list.v1.GetListResponse>}
 */
const methodDescriptor_ListService_GetList = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/GetList',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.GetListRequest,
  proto.ai_poi.list.v1.GetListResponse,
  /**
   * @param {!proto.ai_poi.list.v1.GetListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.GetListResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.GetListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.GetListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.GetListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.getList =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetList',
      request,
      metadata || {},
      methodDescriptor_ListService_GetList,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.GetListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.GetListResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.getList =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetList',
      request,
      metadata || {},
      methodDescriptor_ListService_GetList);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.UpdateListRequest,
 *   !proto.ai_poi.list.v1.UpdateListResponse>}
 */
const methodDescriptor_ListService_UpdateList = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/UpdateList',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.UpdateListRequest,
  proto.ai_poi.list.v1.UpdateListResponse,
  /**
   * @param {!proto.ai_poi.list.v1.UpdateListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.UpdateListResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.UpdateListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.UpdateListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.UpdateListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.updateList =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/UpdateList',
      request,
      metadata || {},
      methodDescriptor_ListService_UpdateList,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.UpdateListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.UpdateListResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.updateList =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/UpdateList',
      request,
      metadata || {},
      methodDescriptor_ListService_UpdateList);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.DeleteListRequest,
 *   !proto.ai_poi.list.v1.DeleteListResponse>}
 */
const methodDescriptor_ListService_DeleteList = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/DeleteList',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.DeleteListRequest,
  proto.ai_poi.list.v1.DeleteListResponse,
  /**
   * @param {!proto.ai_poi.list.v1.DeleteListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.DeleteListResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.DeleteListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.DeleteListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.DeleteListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.deleteList =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/DeleteList',
      request,
      metadata || {},
      methodDescriptor_ListService_DeleteList,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.DeleteListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.DeleteListResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.deleteList =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/DeleteList',
      request,
      metadata || {},
      methodDescriptor_ListService_DeleteList);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.CreateItineraryRequest,
 *   !proto.ai_poi.list.v1.CreateItineraryResponse>}
 */
const methodDescriptor_ListService_CreateItinerary = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/CreateItinerary',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.CreateItineraryRequest,
  proto.ai_poi.list.v1.CreateItineraryResponse,
  /**
   * @param {!proto.ai_poi.list.v1.CreateItineraryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.CreateItineraryResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.CreateItineraryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.CreateItineraryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.CreateItineraryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.createItinerary =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/CreateItinerary',
      request,
      metadata || {},
      methodDescriptor_ListService_CreateItinerary,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.CreateItineraryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.CreateItineraryResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.createItinerary =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/CreateItinerary',
      request,
      metadata || {},
      methodDescriptor_ListService_CreateItinerary);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.AddListItemRequest,
 *   !proto.ai_poi.list.v1.AddListItemResponse>}
 */
const methodDescriptor_ListService_AddListItem = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/AddListItem',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.AddListItemRequest,
  proto.ai_poi.list.v1.AddListItemResponse,
  /**
   * @param {!proto.ai_poi.list.v1.AddListItemRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.AddListItemResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.AddListItemRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.AddListItemResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.AddListItemResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.addListItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/AddListItem',
      request,
      metadata || {},
      methodDescriptor_ListService_AddListItem,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.AddListItemRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.AddListItemResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.addListItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/AddListItem',
      request,
      metadata || {},
      methodDescriptor_ListService_AddListItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.UpdateListItemRequest,
 *   !proto.ai_poi.list.v1.UpdateListItemResponse>}
 */
const methodDescriptor_ListService_UpdateListItem = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/UpdateListItem',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.UpdateListItemRequest,
  proto.ai_poi.list.v1.UpdateListItemResponse,
  /**
   * @param {!proto.ai_poi.list.v1.UpdateListItemRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.UpdateListItemResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.UpdateListItemRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.UpdateListItemResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.UpdateListItemResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.updateListItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/UpdateListItem',
      request,
      metadata || {},
      methodDescriptor_ListService_UpdateListItem,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.UpdateListItemRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.UpdateListItemResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.updateListItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/UpdateListItem',
      request,
      metadata || {},
      methodDescriptor_ListService_UpdateListItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.RemoveListItemRequest,
 *   !proto.ai_poi.list.v1.RemoveListItemResponse>}
 */
const methodDescriptor_ListService_RemoveListItem = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/RemoveListItem',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.RemoveListItemRequest,
  proto.ai_poi.list.v1.RemoveListItemResponse,
  /**
   * @param {!proto.ai_poi.list.v1.RemoveListItemRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.RemoveListItemResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.RemoveListItemRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.RemoveListItemResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.RemoveListItemResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.removeListItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/RemoveListItem',
      request,
      metadata || {},
      methodDescriptor_ListService_RemoveListItem,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.RemoveListItemRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.RemoveListItemResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.removeListItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/RemoveListItem',
      request,
      metadata || {},
      methodDescriptor_ListService_RemoveListItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.GetListItemsRequest,
 *   !proto.ai_poi.list.v1.GetListItemsResponse>}
 */
const methodDescriptor_ListService_GetListItems = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/GetListItems',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.GetListItemsRequest,
  proto.ai_poi.list.v1.GetListItemsResponse,
  /**
   * @param {!proto.ai_poi.list.v1.GetListItemsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.GetListItemsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.GetListItemsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.GetListItemsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.GetListItemsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.getListItems =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetListItems',
      request,
      metadata || {},
      methodDescriptor_ListService_GetListItems,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.GetListItemsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.GetListItemsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.getListItems =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetListItems',
      request,
      metadata || {},
      methodDescriptor_ListService_GetListItems);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.GetListRestaurantsRequest,
 *   !proto.ai_poi.list.v1.GetListRestaurantsResponse>}
 */
const methodDescriptor_ListService_GetListRestaurants = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/GetListRestaurants',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.GetListRestaurantsRequest,
  proto.ai_poi.list.v1.GetListRestaurantsResponse,
  /**
   * @param {!proto.ai_poi.list.v1.GetListRestaurantsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.GetListRestaurantsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.GetListRestaurantsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.GetListRestaurantsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.GetListRestaurantsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.getListRestaurants =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetListRestaurants',
      request,
      metadata || {},
      methodDescriptor_ListService_GetListRestaurants,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.GetListRestaurantsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.GetListRestaurantsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.getListRestaurants =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetListRestaurants',
      request,
      metadata || {},
      methodDescriptor_ListService_GetListRestaurants);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.GetListHotelsRequest,
 *   !proto.ai_poi.list.v1.GetListHotelsResponse>}
 */
const methodDescriptor_ListService_GetListHotels = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/GetListHotels',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.GetListHotelsRequest,
  proto.ai_poi.list.v1.GetListHotelsResponse,
  /**
   * @param {!proto.ai_poi.list.v1.GetListHotelsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.GetListHotelsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.GetListHotelsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.GetListHotelsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.GetListHotelsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.getListHotels =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetListHotels',
      request,
      metadata || {},
      methodDescriptor_ListService_GetListHotels,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.GetListHotelsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.GetListHotelsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.getListHotels =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetListHotels',
      request,
      metadata || {},
      methodDescriptor_ListService_GetListHotels);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.GetListItinerariesRequest,
 *   !proto.ai_poi.list.v1.GetListItinerariesResponse>}
 */
const methodDescriptor_ListService_GetListItineraries = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/GetListItineraries',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.GetListItinerariesRequest,
  proto.ai_poi.list.v1.GetListItinerariesResponse,
  /**
   * @param {!proto.ai_poi.list.v1.GetListItinerariesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.GetListItinerariesResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.GetListItinerariesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.GetListItinerariesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.GetListItinerariesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.getListItineraries =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetListItineraries',
      request,
      metadata || {},
      methodDescriptor_ListService_GetListItineraries,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.GetListItinerariesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.GetListItinerariesResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.getListItineraries =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetListItineraries',
      request,
      metadata || {},
      methodDescriptor_ListService_GetListItineraries);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.SavePublicListRequest,
 *   !proto.ai_poi.list.v1.SavePublicListResponse>}
 */
const methodDescriptor_ListService_SavePublicList = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/SavePublicList',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.SavePublicListRequest,
  proto.ai_poi.list.v1.SavePublicListResponse,
  /**
   * @param {!proto.ai_poi.list.v1.SavePublicListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.SavePublicListResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.SavePublicListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.SavePublicListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.SavePublicListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.savePublicList =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/SavePublicList',
      request,
      metadata || {},
      methodDescriptor_ListService_SavePublicList,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.SavePublicListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.SavePublicListResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.savePublicList =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/SavePublicList',
      request,
      metadata || {},
      methodDescriptor_ListService_SavePublicList);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.UnsaveListRequest,
 *   !proto.ai_poi.list.v1.UnsaveListResponse>}
 */
const methodDescriptor_ListService_UnsaveList = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/UnsaveList',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.UnsaveListRequest,
  proto.ai_poi.list.v1.UnsaveListResponse,
  /**
   * @param {!proto.ai_poi.list.v1.UnsaveListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.UnsaveListResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.UnsaveListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.UnsaveListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.UnsaveListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.unsaveList =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/UnsaveList',
      request,
      metadata || {},
      methodDescriptor_ListService_UnsaveList,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.UnsaveListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.UnsaveListResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.unsaveList =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/UnsaveList',
      request,
      metadata || {},
      methodDescriptor_ListService_UnsaveList);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.GetSavedListsRequest,
 *   !proto.ai_poi.list.v1.GetSavedListsResponse>}
 */
const methodDescriptor_ListService_GetSavedLists = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/GetSavedLists',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.GetSavedListsRequest,
  proto.ai_poi.list.v1.GetSavedListsResponse,
  /**
   * @param {!proto.ai_poi.list.v1.GetSavedListsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.GetSavedListsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.GetSavedListsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.GetSavedListsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.GetSavedListsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.getSavedLists =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetSavedLists',
      request,
      metadata || {},
      methodDescriptor_ListService_GetSavedLists,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.GetSavedListsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.GetSavedListsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.getSavedLists =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/GetSavedLists',
      request,
      metadata || {},
      methodDescriptor_ListService_GetSavedLists);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.list.v1.SearchPublicListsRequest,
 *   !proto.ai_poi.list.v1.SearchPublicListsResponse>}
 */
const methodDescriptor_ListService_SearchPublicLists = new grpc.web.MethodDescriptor(
  '/ai_poi.list.v1.ListService/SearchPublicLists',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.list.v1.SearchPublicListsRequest,
  proto.ai_poi.list.v1.SearchPublicListsResponse,
  /**
   * @param {!proto.ai_poi.list.v1.SearchPublicListsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.list.v1.SearchPublicListsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.list.v1.SearchPublicListsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.list.v1.SearchPublicListsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.list.v1.SearchPublicListsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.list.v1.ListServiceClient.prototype.searchPublicLists =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/SearchPublicLists',
      request,
      metadata || {},
      methodDescriptor_ListService_SearchPublicLists,
      callback);
};


/**
 * @param {!proto.ai_poi.list.v1.SearchPublicListsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.list.v1.SearchPublicListsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.list.v1.ListServicePromiseClient.prototype.searchPublicLists =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.list.v1.ListService/SearchPublicLists',
      request,
      metadata || {},
      methodDescriptor_ListService_SearchPublicLists);
};


module.exports = proto.ai_poi.list.v1;

