/**
 * @fileoverview gRPC-Web generated client stub for ai_poi.poi.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: poi.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.ai_poi = {};
proto.ai_poi.poi = {};
proto.ai_poi.poi.v1 = require('./poi_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai_poi.poi.v1.POIServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai_poi.poi.v1.POIServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.GetPOIsByCityRequest,
 *   !proto.ai_poi.poi.v1.GetPOIsByCityResponse>}
 */
const methodDescriptor_POIService_GetPOIsByCity = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/GetPOIsByCity',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.GetPOIsByCityRequest,
  proto.ai_poi.poi.v1.GetPOIsByCityResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.GetPOIsByCityRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.GetPOIsByCityResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.GetPOIsByCityRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.GetPOIsByCityResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.GetPOIsByCityResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.getPOIsByCity =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetPOIsByCity',
      request,
      metadata || {},
      methodDescriptor_POIService_GetPOIsByCity,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.GetPOIsByCityRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.GetPOIsByCityResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.getPOIsByCity =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetPOIsByCity',
      request,
      metadata || {},
      methodDescriptor_POIService_GetPOIsByCity);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.SearchPOIsRequest,
 *   !proto.ai_poi.poi.v1.SearchPOIsResponse>}
 */
const methodDescriptor_POIService_SearchPOIs = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/SearchPOIs',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.SearchPOIsRequest,
  proto.ai_poi.poi.v1.SearchPOIsResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.SearchPOIsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.SearchPOIsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.SearchPOIsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.SearchPOIsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.SearchPOIsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.searchPOIs =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/SearchPOIs',
      request,
      metadata || {},
      methodDescriptor_POIService_SearchPOIs,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.SearchPOIsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.SearchPOIsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.searchPOIs =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/SearchPOIs',
      request,
      metadata || {},
      methodDescriptor_POIService_SearchPOIs);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.SearchPOIsSemanticRequest,
 *   !proto.ai_poi.poi.v1.SearchPOIsSemanticResponse>}
 */
const methodDescriptor_POIService_SearchPOIsSemantic = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/SearchPOIsSemantic',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.SearchPOIsSemanticRequest,
  proto.ai_poi.poi.v1.SearchPOIsSemanticResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.SearchPOIsSemanticRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.SearchPOIsSemanticResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.SearchPOIsSemanticRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.SearchPOIsSemanticResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.SearchPOIsSemanticResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.searchPOIsSemantic =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/SearchPOIsSemantic',
      request,
      metadata || {},
      methodDescriptor_POIService_SearchPOIsSemantic,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.SearchPOIsSemanticRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.SearchPOIsSemanticResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.searchPOIsSemantic =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/SearchPOIsSemantic',
      request,
      metadata || {},
      methodDescriptor_POIService_SearchPOIsSemantic);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.SearchPOIsSemanticByCityRequest,
 *   !proto.ai_poi.poi.v1.SearchPOIsSemanticResponse>}
 */
const methodDescriptor_POIService_SearchPOIsSemanticByCity = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/SearchPOIsSemanticByCity',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.SearchPOIsSemanticByCityRequest,
  proto.ai_poi.poi.v1.SearchPOIsSemanticResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.SearchPOIsSemanticByCityRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.SearchPOIsSemanticResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.SearchPOIsSemanticByCityRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.SearchPOIsSemanticResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.SearchPOIsSemanticResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.searchPOIsSemanticByCity =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/SearchPOIsSemanticByCity',
      request,
      metadata || {},
      methodDescriptor_POIService_SearchPOIsSemanticByCity,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.SearchPOIsSemanticByCityRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.SearchPOIsSemanticResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.searchPOIsSemanticByCity =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/SearchPOIsSemanticByCity',
      request,
      metadata || {},
      methodDescriptor_POIService_SearchPOIsSemanticByCity);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.SearchPOIsHybridRequest,
 *   !proto.ai_poi.poi.v1.SearchPOIsHybridResponse>}
 */
const methodDescriptor_POIService_SearchPOIsHybrid = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/SearchPOIsHybrid',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.SearchPOIsHybridRequest,
  proto.ai_poi.poi.v1.SearchPOIsHybridResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.SearchPOIsHybridRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.SearchPOIsHybridResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.SearchPOIsHybridRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.SearchPOIsHybridResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.SearchPOIsHybridResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.searchPOIsHybrid =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/SearchPOIsHybrid',
      request,
      metadata || {},
      methodDescriptor_POIService_SearchPOIsHybrid,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.SearchPOIsHybridRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.SearchPOIsHybridResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.searchPOIsHybrid =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/SearchPOIsHybrid',
      request,
      metadata || {},
      methodDescriptor_POIService_SearchPOIsHybrid);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.GetNearbyRecommendationsRequest,
 *   !proto.ai_poi.poi.v1.GetNearbyRecommendationsResponse>}
 */
const methodDescriptor_POIService_GetNearbyRecommendations = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/GetNearbyRecommendations',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.GetNearbyRecommendationsRequest,
  proto.ai_poi.poi.v1.GetNearbyRecommendationsResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.GetNearbyRecommendationsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.GetNearbyRecommendationsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.GetNearbyRecommendationsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.GetNearbyRecommendationsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.GetNearbyRecommendationsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.getNearbyRecommendations =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetNearbyRecommendations',
      request,
      metadata || {},
      methodDescriptor_POIService_GetNearbyRecommendations,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.GetNearbyRecommendationsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.GetNearbyRecommendationsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.getNearbyRecommendations =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetNearbyRecommendations',
      request,
      metadata || {},
      methodDescriptor_POIService_GetNearbyRecommendations);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.DiscoverRestaurantsRequest,
 *   !proto.ai_poi.poi.v1.DiscoverRestaurantsResponse>}
 */
const methodDescriptor_POIService_DiscoverRestaurants = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/DiscoverRestaurants',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.DiscoverRestaurantsRequest,
  proto.ai_poi.poi.v1.DiscoverRestaurantsResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.DiscoverRestaurantsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.DiscoverRestaurantsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.DiscoverRestaurantsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.DiscoverRestaurantsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.DiscoverRestaurantsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.discoverRestaurants =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/DiscoverRestaurants',
      request,
      metadata || {},
      methodDescriptor_POIService_DiscoverRestaurants,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.DiscoverRestaurantsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.DiscoverRestaurantsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.discoverRestaurants =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/DiscoverRestaurants',
      request,
      metadata || {},
      methodDescriptor_POIService_DiscoverRestaurants);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.DiscoverActivitiesRequest,
 *   !proto.ai_poi.poi.v1.DiscoverActivitiesResponse>}
 */
const methodDescriptor_POIService_DiscoverActivities = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/DiscoverActivities',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.DiscoverActivitiesRequest,
  proto.ai_poi.poi.v1.DiscoverActivitiesResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.DiscoverActivitiesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.DiscoverActivitiesResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.DiscoverActivitiesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.DiscoverActivitiesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.DiscoverActivitiesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.discoverActivities =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/DiscoverActivities',
      request,
      metadata || {},
      methodDescriptor_POIService_DiscoverActivities,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.DiscoverActivitiesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.DiscoverActivitiesResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.discoverActivities =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/DiscoverActivities',
      request,
      metadata || {},
      methodDescriptor_POIService_DiscoverActivities);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.DiscoverHotelsRequest,
 *   !proto.ai_poi.poi.v1.DiscoverHotelsResponse>}
 */
const methodDescriptor_POIService_DiscoverHotels = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/DiscoverHotels',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.DiscoverHotelsRequest,
  proto.ai_poi.poi.v1.DiscoverHotelsResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.DiscoverHotelsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.DiscoverHotelsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.DiscoverHotelsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.DiscoverHotelsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.DiscoverHotelsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.discoverHotels =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/DiscoverHotels',
      request,
      metadata || {},
      methodDescriptor_POIService_DiscoverHotels,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.DiscoverHotelsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.DiscoverHotelsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.discoverHotels =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/DiscoverHotels',
      request,
      metadata || {},
      methodDescriptor_POIService_DiscoverHotels);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.DiscoverAttractionsRequest,
 *   !proto.ai_poi.poi.v1.DiscoverAttractionsResponse>}
 */
const methodDescriptor_POIService_DiscoverAttractions = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/DiscoverAttractions',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.DiscoverAttractionsRequest,
  proto.ai_poi.poi.v1.DiscoverAttractionsResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.DiscoverAttractionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.DiscoverAttractionsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.DiscoverAttractionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.DiscoverAttractionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.DiscoverAttractionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.discoverAttractions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/DiscoverAttractions',
      request,
      metadata || {},
      methodDescriptor_POIService_DiscoverAttractions,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.DiscoverAttractionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.DiscoverAttractionsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.discoverAttractions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/DiscoverAttractions',
      request,
      metadata || {},
      methodDescriptor_POIService_DiscoverAttractions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.AddToFavoritesRequest,
 *   !proto.ai_poi.poi.v1.AddToFavoritesResponse>}
 */
const methodDescriptor_POIService_AddToFavorites = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/AddToFavorites',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.AddToFavoritesRequest,
  proto.ai_poi.poi.v1.AddToFavoritesResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.AddToFavoritesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.AddToFavoritesResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.AddToFavoritesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.AddToFavoritesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.AddToFavoritesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.addToFavorites =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/AddToFavorites',
      request,
      metadata || {},
      methodDescriptor_POIService_AddToFavorites,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.AddToFavoritesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.AddToFavoritesResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.addToFavorites =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/AddToFavorites',
      request,
      metadata || {},
      methodDescriptor_POIService_AddToFavorites);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.RemoveFromFavoritesRequest,
 *   !proto.ai_poi.poi.v1.RemoveFromFavoritesResponse>}
 */
const methodDescriptor_POIService_RemoveFromFavorites = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/RemoveFromFavorites',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.RemoveFromFavoritesRequest,
  proto.ai_poi.poi.v1.RemoveFromFavoritesResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.RemoveFromFavoritesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.RemoveFromFavoritesResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.RemoveFromFavoritesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.RemoveFromFavoritesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.RemoveFromFavoritesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.removeFromFavorites =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/RemoveFromFavorites',
      request,
      metadata || {},
      methodDescriptor_POIService_RemoveFromFavorites,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.RemoveFromFavoritesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.RemoveFromFavoritesResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.removeFromFavorites =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/RemoveFromFavorites',
      request,
      metadata || {},
      methodDescriptor_POIService_RemoveFromFavorites);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.GetFavoritesRequest,
 *   !proto.ai_poi.poi.v1.GetFavoritesResponse>}
 */
const methodDescriptor_POIService_GetFavorites = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/GetFavorites',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.GetFavoritesRequest,
  proto.ai_poi.poi.v1.GetFavoritesResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.GetFavoritesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.GetFavoritesResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.GetFavoritesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.GetFavoritesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.GetFavoritesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.getFavorites =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetFavorites',
      request,
      metadata || {},
      methodDescriptor_POIService_GetFavorites,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.GetFavoritesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.GetFavoritesResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.getFavorites =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetFavorites',
      request,
      metadata || {},
      methodDescriptor_POIService_GetFavorites);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.GetItinerariesRequest,
 *   !proto.ai_poi.poi.v1.GetItinerariesResponse>}
 */
const methodDescriptor_POIService_GetItineraries = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/GetItineraries',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.GetItinerariesRequest,
  proto.ai_poi.poi.v1.GetItinerariesResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.GetItinerariesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.GetItinerariesResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.GetItinerariesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.GetItinerariesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.GetItinerariesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.getItineraries =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetItineraries',
      request,
      metadata || {},
      methodDescriptor_POIService_GetItineraries,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.GetItinerariesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.GetItinerariesResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.getItineraries =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetItineraries',
      request,
      metadata || {},
      methodDescriptor_POIService_GetItineraries);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.GetItineraryRequest,
 *   !proto.ai_poi.poi.v1.GetItineraryResponse>}
 */
const methodDescriptor_POIService_GetItinerary = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/GetItinerary',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.GetItineraryRequest,
  proto.ai_poi.poi.v1.GetItineraryResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.GetItineraryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.GetItineraryResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.GetItineraryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.GetItineraryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.GetItineraryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.getItinerary =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetItinerary',
      request,
      metadata || {},
      methodDescriptor_POIService_GetItinerary,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.GetItineraryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.GetItineraryResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.getItinerary =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetItinerary',
      request,
      metadata || {},
      methodDescriptor_POIService_GetItinerary);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.UpdateItineraryRequest,
 *   !proto.ai_poi.poi.v1.UpdateItineraryResponse>}
 */
const methodDescriptor_POIService_UpdateItinerary = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/UpdateItinerary',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.UpdateItineraryRequest,
  proto.ai_poi.poi.v1.UpdateItineraryResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.UpdateItineraryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.UpdateItineraryResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.UpdateItineraryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.UpdateItineraryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.UpdateItineraryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.updateItinerary =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/UpdateItinerary',
      request,
      metadata || {},
      methodDescriptor_POIService_UpdateItinerary,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.UpdateItineraryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.UpdateItineraryResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.updateItinerary =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/UpdateItinerary',
      request,
      metadata || {},
      methodDescriptor_POIService_UpdateItinerary);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.poi.v1.GenerateEmbeddingsRequest,
 *   !proto.ai_poi.poi.v1.GenerateEmbeddingsResponse>}
 */
const methodDescriptor_POIService_GenerateEmbeddings = new grpc.web.MethodDescriptor(
  '/ai_poi.poi.v1.POIService/GenerateEmbeddings',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.poi.v1.GenerateEmbeddingsRequest,
  proto.ai_poi.poi.v1.GenerateEmbeddingsResponse,
  /**
   * @param {!proto.ai_poi.poi.v1.GenerateEmbeddingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.poi.v1.GenerateEmbeddingsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.poi.v1.GenerateEmbeddingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.poi.v1.GenerateEmbeddingsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.poi.v1.GenerateEmbeddingsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.poi.v1.POIServiceClient.prototype.generateEmbeddings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/GenerateEmbeddings',
      request,
      metadata || {},
      methodDescriptor_POIService_GenerateEmbeddings,
      callback);
};


/**
 * @param {!proto.ai_poi.poi.v1.GenerateEmbeddingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.poi.v1.GenerateEmbeddingsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.poi.v1.POIServicePromiseClient.prototype.generateEmbeddings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.poi.v1.POIService/GenerateEmbeddings',
      request,
      metadata || {},
      methodDescriptor_POIService_GenerateEmbeddings);
};


module.exports = proto.ai_poi.poi.v1;

