/**
 * @fileoverview gRPC-Web generated client stub for ai_poi.poi.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: poi.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as poi_pb from './poi_pb'; // proto import: "poi.proto"


export class POIServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetPOIsByCity = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/GetPOIsByCity',
    grpcWeb.MethodType.UNARY,
    poi_pb.GetPOIsByCityRequest,
    poi_pb.GetPOIsByCityResponse,
    (request: poi_pb.GetPOIsByCityRequest) => {
      return request.serializeBinary();
    },
    poi_pb.GetPOIsByCityResponse.deserializeBinary
  );

  getPOIsByCity(
    request: poi_pb.GetPOIsByCityRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.GetPOIsByCityResponse>;

  getPOIsByCity(
    request: poi_pb.GetPOIsByCityRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.GetPOIsByCityResponse) => void): grpcWeb.ClientReadableStream<poi_pb.GetPOIsByCityResponse>;

  getPOIsByCity(
    request: poi_pb.GetPOIsByCityRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.GetPOIsByCityResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/GetPOIsByCity',
        request,
        metadata || {},
        this.methodDescriptorGetPOIsByCity,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetPOIsByCity',
    request,
    metadata || {},
    this.methodDescriptorGetPOIsByCity);
  }

  methodDescriptorSearchPOIs = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/SearchPOIs',
    grpcWeb.MethodType.UNARY,
    poi_pb.SearchPOIsRequest,
    poi_pb.SearchPOIsResponse,
    (request: poi_pb.SearchPOIsRequest) => {
      return request.serializeBinary();
    },
    poi_pb.SearchPOIsResponse.deserializeBinary
  );

  searchPOIs(
    request: poi_pb.SearchPOIsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.SearchPOIsResponse>;

  searchPOIs(
    request: poi_pb.SearchPOIsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.SearchPOIsResponse) => void): grpcWeb.ClientReadableStream<poi_pb.SearchPOIsResponse>;

  searchPOIs(
    request: poi_pb.SearchPOIsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.SearchPOIsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/SearchPOIs',
        request,
        metadata || {},
        this.methodDescriptorSearchPOIs,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/SearchPOIs',
    request,
    metadata || {},
    this.methodDescriptorSearchPOIs);
  }

  methodDescriptorSearchPOIsSemantic = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/SearchPOIsSemantic',
    grpcWeb.MethodType.UNARY,
    poi_pb.SearchPOIsSemanticRequest,
    poi_pb.SearchPOIsSemanticResponse,
    (request: poi_pb.SearchPOIsSemanticRequest) => {
      return request.serializeBinary();
    },
    poi_pb.SearchPOIsSemanticResponse.deserializeBinary
  );

  searchPOIsSemantic(
    request: poi_pb.SearchPOIsSemanticRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.SearchPOIsSemanticResponse>;

  searchPOIsSemantic(
    request: poi_pb.SearchPOIsSemanticRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.SearchPOIsSemanticResponse) => void): grpcWeb.ClientReadableStream<poi_pb.SearchPOIsSemanticResponse>;

  searchPOIsSemantic(
    request: poi_pb.SearchPOIsSemanticRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.SearchPOIsSemanticResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/SearchPOIsSemantic',
        request,
        metadata || {},
        this.methodDescriptorSearchPOIsSemantic,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/SearchPOIsSemantic',
    request,
    metadata || {},
    this.methodDescriptorSearchPOIsSemantic);
  }

  methodDescriptorSearchPOIsSemanticByCity = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/SearchPOIsSemanticByCity',
    grpcWeb.MethodType.UNARY,
    poi_pb.SearchPOIsSemanticByCityRequest,
    poi_pb.SearchPOIsSemanticResponse,
    (request: poi_pb.SearchPOIsSemanticByCityRequest) => {
      return request.serializeBinary();
    },
    poi_pb.SearchPOIsSemanticResponse.deserializeBinary
  );

  searchPOIsSemanticByCity(
    request: poi_pb.SearchPOIsSemanticByCityRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.SearchPOIsSemanticResponse>;

  searchPOIsSemanticByCity(
    request: poi_pb.SearchPOIsSemanticByCityRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.SearchPOIsSemanticResponse) => void): grpcWeb.ClientReadableStream<poi_pb.SearchPOIsSemanticResponse>;

  searchPOIsSemanticByCity(
    request: poi_pb.SearchPOIsSemanticByCityRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.SearchPOIsSemanticResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/SearchPOIsSemanticByCity',
        request,
        metadata || {},
        this.methodDescriptorSearchPOIsSemanticByCity,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/SearchPOIsSemanticByCity',
    request,
    metadata || {},
    this.methodDescriptorSearchPOIsSemanticByCity);
  }

  methodDescriptorSearchPOIsHybrid = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/SearchPOIsHybrid',
    grpcWeb.MethodType.UNARY,
    poi_pb.SearchPOIsHybridRequest,
    poi_pb.SearchPOIsHybridResponse,
    (request: poi_pb.SearchPOIsHybridRequest) => {
      return request.serializeBinary();
    },
    poi_pb.SearchPOIsHybridResponse.deserializeBinary
  );

  searchPOIsHybrid(
    request: poi_pb.SearchPOIsHybridRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.SearchPOIsHybridResponse>;

  searchPOIsHybrid(
    request: poi_pb.SearchPOIsHybridRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.SearchPOIsHybridResponse) => void): grpcWeb.ClientReadableStream<poi_pb.SearchPOIsHybridResponse>;

  searchPOIsHybrid(
    request: poi_pb.SearchPOIsHybridRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.SearchPOIsHybridResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/SearchPOIsHybrid',
        request,
        metadata || {},
        this.methodDescriptorSearchPOIsHybrid,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/SearchPOIsHybrid',
    request,
    metadata || {},
    this.methodDescriptorSearchPOIsHybrid);
  }

  methodDescriptorGetNearbyRecommendations = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/GetNearbyRecommendations',
    grpcWeb.MethodType.UNARY,
    poi_pb.GetNearbyRecommendationsRequest,
    poi_pb.GetNearbyRecommendationsResponse,
    (request: poi_pb.GetNearbyRecommendationsRequest) => {
      return request.serializeBinary();
    },
    poi_pb.GetNearbyRecommendationsResponse.deserializeBinary
  );

  getNearbyRecommendations(
    request: poi_pb.GetNearbyRecommendationsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.GetNearbyRecommendationsResponse>;

  getNearbyRecommendations(
    request: poi_pb.GetNearbyRecommendationsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.GetNearbyRecommendationsResponse) => void): grpcWeb.ClientReadableStream<poi_pb.GetNearbyRecommendationsResponse>;

  getNearbyRecommendations(
    request: poi_pb.GetNearbyRecommendationsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.GetNearbyRecommendationsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/GetNearbyRecommendations',
        request,
        metadata || {},
        this.methodDescriptorGetNearbyRecommendations,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetNearbyRecommendations',
    request,
    metadata || {},
    this.methodDescriptorGetNearbyRecommendations);
  }

  methodDescriptorDiscoverRestaurants = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/DiscoverRestaurants',
    grpcWeb.MethodType.UNARY,
    poi_pb.DiscoverRestaurantsRequest,
    poi_pb.DiscoverRestaurantsResponse,
    (request: poi_pb.DiscoverRestaurantsRequest) => {
      return request.serializeBinary();
    },
    poi_pb.DiscoverRestaurantsResponse.deserializeBinary
  );

  discoverRestaurants(
    request: poi_pb.DiscoverRestaurantsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.DiscoverRestaurantsResponse>;

  discoverRestaurants(
    request: poi_pb.DiscoverRestaurantsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.DiscoverRestaurantsResponse) => void): grpcWeb.ClientReadableStream<poi_pb.DiscoverRestaurantsResponse>;

  discoverRestaurants(
    request: poi_pb.DiscoverRestaurantsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.DiscoverRestaurantsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/DiscoverRestaurants',
        request,
        metadata || {},
        this.methodDescriptorDiscoverRestaurants,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/DiscoverRestaurants',
    request,
    metadata || {},
    this.methodDescriptorDiscoverRestaurants);
  }

  methodDescriptorDiscoverActivities = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/DiscoverActivities',
    grpcWeb.MethodType.UNARY,
    poi_pb.DiscoverActivitiesRequest,
    poi_pb.DiscoverActivitiesResponse,
    (request: poi_pb.DiscoverActivitiesRequest) => {
      return request.serializeBinary();
    },
    poi_pb.DiscoverActivitiesResponse.deserializeBinary
  );

  discoverActivities(
    request: poi_pb.DiscoverActivitiesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.DiscoverActivitiesResponse>;

  discoverActivities(
    request: poi_pb.DiscoverActivitiesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.DiscoverActivitiesResponse) => void): grpcWeb.ClientReadableStream<poi_pb.DiscoverActivitiesResponse>;

  discoverActivities(
    request: poi_pb.DiscoverActivitiesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.DiscoverActivitiesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/DiscoverActivities',
        request,
        metadata || {},
        this.methodDescriptorDiscoverActivities,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/DiscoverActivities',
    request,
    metadata || {},
    this.methodDescriptorDiscoverActivities);
  }

  methodDescriptorDiscoverHotels = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/DiscoverHotels',
    grpcWeb.MethodType.UNARY,
    poi_pb.DiscoverHotelsRequest,
    poi_pb.DiscoverHotelsResponse,
    (request: poi_pb.DiscoverHotelsRequest) => {
      return request.serializeBinary();
    },
    poi_pb.DiscoverHotelsResponse.deserializeBinary
  );

  discoverHotels(
    request: poi_pb.DiscoverHotelsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.DiscoverHotelsResponse>;

  discoverHotels(
    request: poi_pb.DiscoverHotelsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.DiscoverHotelsResponse) => void): grpcWeb.ClientReadableStream<poi_pb.DiscoverHotelsResponse>;

  discoverHotels(
    request: poi_pb.DiscoverHotelsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.DiscoverHotelsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/DiscoverHotels',
        request,
        metadata || {},
        this.methodDescriptorDiscoverHotels,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/DiscoverHotels',
    request,
    metadata || {},
    this.methodDescriptorDiscoverHotels);
  }

  methodDescriptorDiscoverAttractions = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/DiscoverAttractions',
    grpcWeb.MethodType.UNARY,
    poi_pb.DiscoverAttractionsRequest,
    poi_pb.DiscoverAttractionsResponse,
    (request: poi_pb.DiscoverAttractionsRequest) => {
      return request.serializeBinary();
    },
    poi_pb.DiscoverAttractionsResponse.deserializeBinary
  );

  discoverAttractions(
    request: poi_pb.DiscoverAttractionsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.DiscoverAttractionsResponse>;

  discoverAttractions(
    request: poi_pb.DiscoverAttractionsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.DiscoverAttractionsResponse) => void): grpcWeb.ClientReadableStream<poi_pb.DiscoverAttractionsResponse>;

  discoverAttractions(
    request: poi_pb.DiscoverAttractionsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.DiscoverAttractionsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/DiscoverAttractions',
        request,
        metadata || {},
        this.methodDescriptorDiscoverAttractions,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/DiscoverAttractions',
    request,
    metadata || {},
    this.methodDescriptorDiscoverAttractions);
  }

  methodDescriptorAddToFavorites = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/AddToFavorites',
    grpcWeb.MethodType.UNARY,
    poi_pb.AddToFavoritesRequest,
    poi_pb.AddToFavoritesResponse,
    (request: poi_pb.AddToFavoritesRequest) => {
      return request.serializeBinary();
    },
    poi_pb.AddToFavoritesResponse.deserializeBinary
  );

  addToFavorites(
    request: poi_pb.AddToFavoritesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.AddToFavoritesResponse>;

  addToFavorites(
    request: poi_pb.AddToFavoritesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.AddToFavoritesResponse) => void): grpcWeb.ClientReadableStream<poi_pb.AddToFavoritesResponse>;

  addToFavorites(
    request: poi_pb.AddToFavoritesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.AddToFavoritesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/AddToFavorites',
        request,
        metadata || {},
        this.methodDescriptorAddToFavorites,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/AddToFavorites',
    request,
    metadata || {},
    this.methodDescriptorAddToFavorites);
  }

  methodDescriptorRemoveFromFavorites = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/RemoveFromFavorites',
    grpcWeb.MethodType.UNARY,
    poi_pb.RemoveFromFavoritesRequest,
    poi_pb.RemoveFromFavoritesResponse,
    (request: poi_pb.RemoveFromFavoritesRequest) => {
      return request.serializeBinary();
    },
    poi_pb.RemoveFromFavoritesResponse.deserializeBinary
  );

  removeFromFavorites(
    request: poi_pb.RemoveFromFavoritesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.RemoveFromFavoritesResponse>;

  removeFromFavorites(
    request: poi_pb.RemoveFromFavoritesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.RemoveFromFavoritesResponse) => void): grpcWeb.ClientReadableStream<poi_pb.RemoveFromFavoritesResponse>;

  removeFromFavorites(
    request: poi_pb.RemoveFromFavoritesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.RemoveFromFavoritesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/RemoveFromFavorites',
        request,
        metadata || {},
        this.methodDescriptorRemoveFromFavorites,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/RemoveFromFavorites',
    request,
    metadata || {},
    this.methodDescriptorRemoveFromFavorites);
  }

  methodDescriptorGetFavorites = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/GetFavorites',
    grpcWeb.MethodType.UNARY,
    poi_pb.GetFavoritesRequest,
    poi_pb.GetFavoritesResponse,
    (request: poi_pb.GetFavoritesRequest) => {
      return request.serializeBinary();
    },
    poi_pb.GetFavoritesResponse.deserializeBinary
  );

  getFavorites(
    request: poi_pb.GetFavoritesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.GetFavoritesResponse>;

  getFavorites(
    request: poi_pb.GetFavoritesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.GetFavoritesResponse) => void): grpcWeb.ClientReadableStream<poi_pb.GetFavoritesResponse>;

  getFavorites(
    request: poi_pb.GetFavoritesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.GetFavoritesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/GetFavorites',
        request,
        metadata || {},
        this.methodDescriptorGetFavorites,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetFavorites',
    request,
    metadata || {},
    this.methodDescriptorGetFavorites);
  }

  methodDescriptorGetItineraries = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/GetItineraries',
    grpcWeb.MethodType.UNARY,
    poi_pb.GetItinerariesRequest,
    poi_pb.GetItinerariesResponse,
    (request: poi_pb.GetItinerariesRequest) => {
      return request.serializeBinary();
    },
    poi_pb.GetItinerariesResponse.deserializeBinary
  );

  getItineraries(
    request: poi_pb.GetItinerariesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.GetItinerariesResponse>;

  getItineraries(
    request: poi_pb.GetItinerariesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.GetItinerariesResponse) => void): grpcWeb.ClientReadableStream<poi_pb.GetItinerariesResponse>;

  getItineraries(
    request: poi_pb.GetItinerariesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.GetItinerariesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/GetItineraries',
        request,
        metadata || {},
        this.methodDescriptorGetItineraries,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetItineraries',
    request,
    metadata || {},
    this.methodDescriptorGetItineraries);
  }

  methodDescriptorGetItinerary = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/GetItinerary',
    grpcWeb.MethodType.UNARY,
    poi_pb.GetItineraryRequest,
    poi_pb.GetItineraryResponse,
    (request: poi_pb.GetItineraryRequest) => {
      return request.serializeBinary();
    },
    poi_pb.GetItineraryResponse.deserializeBinary
  );

  getItinerary(
    request: poi_pb.GetItineraryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.GetItineraryResponse>;

  getItinerary(
    request: poi_pb.GetItineraryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.GetItineraryResponse) => void): grpcWeb.ClientReadableStream<poi_pb.GetItineraryResponse>;

  getItinerary(
    request: poi_pb.GetItineraryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.GetItineraryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/GetItinerary',
        request,
        metadata || {},
        this.methodDescriptorGetItinerary,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/GetItinerary',
    request,
    metadata || {},
    this.methodDescriptorGetItinerary);
  }

  methodDescriptorUpdateItinerary = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/UpdateItinerary',
    grpcWeb.MethodType.UNARY,
    poi_pb.UpdateItineraryRequest,
    poi_pb.UpdateItineraryResponse,
    (request: poi_pb.UpdateItineraryRequest) => {
      return request.serializeBinary();
    },
    poi_pb.UpdateItineraryResponse.deserializeBinary
  );

  updateItinerary(
    request: poi_pb.UpdateItineraryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.UpdateItineraryResponse>;

  updateItinerary(
    request: poi_pb.UpdateItineraryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.UpdateItineraryResponse) => void): grpcWeb.ClientReadableStream<poi_pb.UpdateItineraryResponse>;

  updateItinerary(
    request: poi_pb.UpdateItineraryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.UpdateItineraryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/UpdateItinerary',
        request,
        metadata || {},
        this.methodDescriptorUpdateItinerary,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/UpdateItinerary',
    request,
    metadata || {},
    this.methodDescriptorUpdateItinerary);
  }

  methodDescriptorGenerateEmbeddings = new grpcWeb.MethodDescriptor(
    '/ai_poi.poi.v1.POIService/GenerateEmbeddings',
    grpcWeb.MethodType.UNARY,
    poi_pb.GenerateEmbeddingsRequest,
    poi_pb.GenerateEmbeddingsResponse,
    (request: poi_pb.GenerateEmbeddingsRequest) => {
      return request.serializeBinary();
    },
    poi_pb.GenerateEmbeddingsResponse.deserializeBinary
  );

  generateEmbeddings(
    request: poi_pb.GenerateEmbeddingsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<poi_pb.GenerateEmbeddingsResponse>;

  generateEmbeddings(
    request: poi_pb.GenerateEmbeddingsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: poi_pb.GenerateEmbeddingsResponse) => void): grpcWeb.ClientReadableStream<poi_pb.GenerateEmbeddingsResponse>;

  generateEmbeddings(
    request: poi_pb.GenerateEmbeddingsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: poi_pb.GenerateEmbeddingsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.poi.v1.POIService/GenerateEmbeddings',
        request,
        metadata || {},
        this.methodDescriptorGenerateEmbeddings,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.poi.v1.POIService/GenerateEmbeddings',
    request,
    metadata || {},
    this.methodDescriptorGenerateEmbeddings);
  }

}

