/**
 * @fileoverview gRPC-Web generated client stub for ai_poi.profiles.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: profiles.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.ai_poi = {};
proto.ai_poi.profiles = {};
proto.ai_poi.profiles.v1 = require('./profiles_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai_poi.profiles.v1.ProfilesServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai_poi.profiles.v1.ProfilesServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.profiles.v1.GetSearchProfilesRequest,
 *   !proto.ai_poi.profiles.v1.GetSearchProfilesResponse>}
 */
const methodDescriptor_ProfilesService_GetSearchProfiles = new grpc.web.MethodDescriptor(
  '/ai_poi.profiles.v1.ProfilesService/GetSearchProfiles',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.profiles.v1.GetSearchProfilesRequest,
  proto.ai_poi.profiles.v1.GetSearchProfilesResponse,
  /**
   * @param {!proto.ai_poi.profiles.v1.GetSearchProfilesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.profiles.v1.GetSearchProfilesResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.profiles.v1.GetSearchProfilesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.profiles.v1.GetSearchProfilesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.profiles.v1.GetSearchProfilesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.profiles.v1.ProfilesServiceClient.prototype.getSearchProfiles =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/GetSearchProfiles',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_GetSearchProfiles,
      callback);
};


/**
 * @param {!proto.ai_poi.profiles.v1.GetSearchProfilesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.profiles.v1.GetSearchProfilesResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.profiles.v1.ProfilesServicePromiseClient.prototype.getSearchProfiles =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/GetSearchProfiles',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_GetSearchProfiles);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.profiles.v1.GetSearchProfileRequest,
 *   !proto.ai_poi.profiles.v1.GetSearchProfileResponse>}
 */
const methodDescriptor_ProfilesService_GetSearchProfile = new grpc.web.MethodDescriptor(
  '/ai_poi.profiles.v1.ProfilesService/GetSearchProfile',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.profiles.v1.GetSearchProfileRequest,
  proto.ai_poi.profiles.v1.GetSearchProfileResponse,
  /**
   * @param {!proto.ai_poi.profiles.v1.GetSearchProfileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.profiles.v1.GetSearchProfileResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.profiles.v1.GetSearchProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.profiles.v1.GetSearchProfileResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.profiles.v1.GetSearchProfileResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.profiles.v1.ProfilesServiceClient.prototype.getSearchProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/GetSearchProfile',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_GetSearchProfile,
      callback);
};


/**
 * @param {!proto.ai_poi.profiles.v1.GetSearchProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.profiles.v1.GetSearchProfileResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.profiles.v1.ProfilesServicePromiseClient.prototype.getSearchProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/GetSearchProfile',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_GetSearchProfile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.profiles.v1.GetDefaultSearchProfileRequest,
 *   !proto.ai_poi.profiles.v1.GetDefaultSearchProfileResponse>}
 */
const methodDescriptor_ProfilesService_GetDefaultSearchProfile = new grpc.web.MethodDescriptor(
  '/ai_poi.profiles.v1.ProfilesService/GetDefaultSearchProfile',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.profiles.v1.GetDefaultSearchProfileRequest,
  proto.ai_poi.profiles.v1.GetDefaultSearchProfileResponse,
  /**
   * @param {!proto.ai_poi.profiles.v1.GetDefaultSearchProfileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.profiles.v1.GetDefaultSearchProfileResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.profiles.v1.GetDefaultSearchProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.profiles.v1.GetDefaultSearchProfileResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.profiles.v1.GetDefaultSearchProfileResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.profiles.v1.ProfilesServiceClient.prototype.getDefaultSearchProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/GetDefaultSearchProfile',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_GetDefaultSearchProfile,
      callback);
};


/**
 * @param {!proto.ai_poi.profiles.v1.GetDefaultSearchProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.profiles.v1.GetDefaultSearchProfileResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.profiles.v1.ProfilesServicePromiseClient.prototype.getDefaultSearchProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/GetDefaultSearchProfile',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_GetDefaultSearchProfile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.profiles.v1.CreateSearchProfileRequest,
 *   !proto.ai_poi.profiles.v1.CreateSearchProfileResponse>}
 */
const methodDescriptor_ProfilesService_CreateSearchProfile = new grpc.web.MethodDescriptor(
  '/ai_poi.profiles.v1.ProfilesService/CreateSearchProfile',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.profiles.v1.CreateSearchProfileRequest,
  proto.ai_poi.profiles.v1.CreateSearchProfileResponse,
  /**
   * @param {!proto.ai_poi.profiles.v1.CreateSearchProfileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.profiles.v1.CreateSearchProfileResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.profiles.v1.CreateSearchProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.profiles.v1.CreateSearchProfileResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.profiles.v1.CreateSearchProfileResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.profiles.v1.ProfilesServiceClient.prototype.createSearchProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/CreateSearchProfile',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_CreateSearchProfile,
      callback);
};


/**
 * @param {!proto.ai_poi.profiles.v1.CreateSearchProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.profiles.v1.CreateSearchProfileResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.profiles.v1.ProfilesServicePromiseClient.prototype.createSearchProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/CreateSearchProfile',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_CreateSearchProfile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.profiles.v1.UpdateSearchProfileRequest,
 *   !proto.ai_poi.profiles.v1.UpdateSearchProfileResponse>}
 */
const methodDescriptor_ProfilesService_UpdateSearchProfile = new grpc.web.MethodDescriptor(
  '/ai_poi.profiles.v1.ProfilesService/UpdateSearchProfile',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.profiles.v1.UpdateSearchProfileRequest,
  proto.ai_poi.profiles.v1.UpdateSearchProfileResponse,
  /**
   * @param {!proto.ai_poi.profiles.v1.UpdateSearchProfileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.profiles.v1.UpdateSearchProfileResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.profiles.v1.UpdateSearchProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.profiles.v1.UpdateSearchProfileResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.profiles.v1.UpdateSearchProfileResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.profiles.v1.ProfilesServiceClient.prototype.updateSearchProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/UpdateSearchProfile',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_UpdateSearchProfile,
      callback);
};


/**
 * @param {!proto.ai_poi.profiles.v1.UpdateSearchProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.profiles.v1.UpdateSearchProfileResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.profiles.v1.ProfilesServicePromiseClient.prototype.updateSearchProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/UpdateSearchProfile',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_UpdateSearchProfile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.profiles.v1.DeleteSearchProfileRequest,
 *   !proto.ai_poi.profiles.v1.DeleteSearchProfileResponse>}
 */
const methodDescriptor_ProfilesService_DeleteSearchProfile = new grpc.web.MethodDescriptor(
  '/ai_poi.profiles.v1.ProfilesService/DeleteSearchProfile',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.profiles.v1.DeleteSearchProfileRequest,
  proto.ai_poi.profiles.v1.DeleteSearchProfileResponse,
  /**
   * @param {!proto.ai_poi.profiles.v1.DeleteSearchProfileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.profiles.v1.DeleteSearchProfileResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.profiles.v1.DeleteSearchProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.profiles.v1.DeleteSearchProfileResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.profiles.v1.DeleteSearchProfileResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.profiles.v1.ProfilesServiceClient.prototype.deleteSearchProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/DeleteSearchProfile',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_DeleteSearchProfile,
      callback);
};


/**
 * @param {!proto.ai_poi.profiles.v1.DeleteSearchProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.profiles.v1.DeleteSearchProfileResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.profiles.v1.ProfilesServicePromiseClient.prototype.deleteSearchProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/DeleteSearchProfile',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_DeleteSearchProfile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.profiles.v1.SetDefaultSearchProfileRequest,
 *   !proto.ai_poi.profiles.v1.SetDefaultSearchProfileResponse>}
 */
const methodDescriptor_ProfilesService_SetDefaultSearchProfile = new grpc.web.MethodDescriptor(
  '/ai_poi.profiles.v1.ProfilesService/SetDefaultSearchProfile',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.profiles.v1.SetDefaultSearchProfileRequest,
  proto.ai_poi.profiles.v1.SetDefaultSearchProfileResponse,
  /**
   * @param {!proto.ai_poi.profiles.v1.SetDefaultSearchProfileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.profiles.v1.SetDefaultSearchProfileResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.profiles.v1.SetDefaultSearchProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.profiles.v1.SetDefaultSearchProfileResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.profiles.v1.SetDefaultSearchProfileResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.profiles.v1.ProfilesServiceClient.prototype.setDefaultSearchProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/SetDefaultSearchProfile',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_SetDefaultSearchProfile,
      callback);
};


/**
 * @param {!proto.ai_poi.profiles.v1.SetDefaultSearchProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.profiles.v1.SetDefaultSearchProfileResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.profiles.v1.ProfilesServicePromiseClient.prototype.setDefaultSearchProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/SetDefaultSearchProfile',
      request,
      metadata || {},
      methodDescriptor_ProfilesService_SetDefaultSearchProfile);
};


module.exports = proto.ai_poi.profiles.v1;

