/**
 * @fileoverview gRPC-Web generated client stub for ai_poi.profiles.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: profiles.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as profiles_pb from './profiles_pb'; // proto import: "profiles.proto"


export class ProfilesServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetSearchProfiles = new grpcWeb.MethodDescriptor(
    '/ai_poi.profiles.v1.ProfilesService/GetSearchProfiles',
    grpcWeb.MethodType.UNARY,
    profiles_pb.GetSearchProfilesRequest,
    profiles_pb.GetSearchProfilesResponse,
    (request: profiles_pb.GetSearchProfilesRequest) => {
      return request.serializeBinary();
    },
    profiles_pb.GetSearchProfilesResponse.deserializeBinary
  );

  getSearchProfiles(
    request: profiles_pb.GetSearchProfilesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<profiles_pb.GetSearchProfilesResponse>;

  getSearchProfiles(
    request: profiles_pb.GetSearchProfilesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: profiles_pb.GetSearchProfilesResponse) => void): grpcWeb.ClientReadableStream<profiles_pb.GetSearchProfilesResponse>;

  getSearchProfiles(
    request: profiles_pb.GetSearchProfilesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: profiles_pb.GetSearchProfilesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.profiles.v1.ProfilesService/GetSearchProfiles',
        request,
        metadata || {},
        this.methodDescriptorGetSearchProfiles,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/GetSearchProfiles',
    request,
    metadata || {},
    this.methodDescriptorGetSearchProfiles);
  }

  methodDescriptorGetSearchProfile = new grpcWeb.MethodDescriptor(
    '/ai_poi.profiles.v1.ProfilesService/GetSearchProfile',
    grpcWeb.MethodType.UNARY,
    profiles_pb.GetSearchProfileRequest,
    profiles_pb.GetSearchProfileResponse,
    (request: profiles_pb.GetSearchProfileRequest) => {
      return request.serializeBinary();
    },
    profiles_pb.GetSearchProfileResponse.deserializeBinary
  );

  getSearchProfile(
    request: profiles_pb.GetSearchProfileRequest,
    metadata?: grpcWeb.Metadata | null): Promise<profiles_pb.GetSearchProfileResponse>;

  getSearchProfile(
    request: profiles_pb.GetSearchProfileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: profiles_pb.GetSearchProfileResponse) => void): grpcWeb.ClientReadableStream<profiles_pb.GetSearchProfileResponse>;

  getSearchProfile(
    request: profiles_pb.GetSearchProfileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: profiles_pb.GetSearchProfileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.profiles.v1.ProfilesService/GetSearchProfile',
        request,
        metadata || {},
        this.methodDescriptorGetSearchProfile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/GetSearchProfile',
    request,
    metadata || {},
    this.methodDescriptorGetSearchProfile);
  }

  methodDescriptorGetDefaultSearchProfile = new grpcWeb.MethodDescriptor(
    '/ai_poi.profiles.v1.ProfilesService/GetDefaultSearchProfile',
    grpcWeb.MethodType.UNARY,
    profiles_pb.GetDefaultSearchProfileRequest,
    profiles_pb.GetDefaultSearchProfileResponse,
    (request: profiles_pb.GetDefaultSearchProfileRequest) => {
      return request.serializeBinary();
    },
    profiles_pb.GetDefaultSearchProfileResponse.deserializeBinary
  );

  getDefaultSearchProfile(
    request: profiles_pb.GetDefaultSearchProfileRequest,
    metadata?: grpcWeb.Metadata | null): Promise<profiles_pb.GetDefaultSearchProfileResponse>;

  getDefaultSearchProfile(
    request: profiles_pb.GetDefaultSearchProfileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: profiles_pb.GetDefaultSearchProfileResponse) => void): grpcWeb.ClientReadableStream<profiles_pb.GetDefaultSearchProfileResponse>;

  getDefaultSearchProfile(
    request: profiles_pb.GetDefaultSearchProfileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: profiles_pb.GetDefaultSearchProfileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.profiles.v1.ProfilesService/GetDefaultSearchProfile',
        request,
        metadata || {},
        this.methodDescriptorGetDefaultSearchProfile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/GetDefaultSearchProfile',
    request,
    metadata || {},
    this.methodDescriptorGetDefaultSearchProfile);
  }

  methodDescriptorCreateSearchProfile = new grpcWeb.MethodDescriptor(
    '/ai_poi.profiles.v1.ProfilesService/CreateSearchProfile',
    grpcWeb.MethodType.UNARY,
    profiles_pb.CreateSearchProfileRequest,
    profiles_pb.CreateSearchProfileResponse,
    (request: profiles_pb.CreateSearchProfileRequest) => {
      return request.serializeBinary();
    },
    profiles_pb.CreateSearchProfileResponse.deserializeBinary
  );

  createSearchProfile(
    request: profiles_pb.CreateSearchProfileRequest,
    metadata?: grpcWeb.Metadata | null): Promise<profiles_pb.CreateSearchProfileResponse>;

  createSearchProfile(
    request: profiles_pb.CreateSearchProfileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: profiles_pb.CreateSearchProfileResponse) => void): grpcWeb.ClientReadableStream<profiles_pb.CreateSearchProfileResponse>;

  createSearchProfile(
    request: profiles_pb.CreateSearchProfileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: profiles_pb.CreateSearchProfileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.profiles.v1.ProfilesService/CreateSearchProfile',
        request,
        metadata || {},
        this.methodDescriptorCreateSearchProfile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/CreateSearchProfile',
    request,
    metadata || {},
    this.methodDescriptorCreateSearchProfile);
  }

  methodDescriptorUpdateSearchProfile = new grpcWeb.MethodDescriptor(
    '/ai_poi.profiles.v1.ProfilesService/UpdateSearchProfile',
    grpcWeb.MethodType.UNARY,
    profiles_pb.UpdateSearchProfileRequest,
    profiles_pb.UpdateSearchProfileResponse,
    (request: profiles_pb.UpdateSearchProfileRequest) => {
      return request.serializeBinary();
    },
    profiles_pb.UpdateSearchProfileResponse.deserializeBinary
  );

  updateSearchProfile(
    request: profiles_pb.UpdateSearchProfileRequest,
    metadata?: grpcWeb.Metadata | null): Promise<profiles_pb.UpdateSearchProfileResponse>;

  updateSearchProfile(
    request: profiles_pb.UpdateSearchProfileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: profiles_pb.UpdateSearchProfileResponse) => void): grpcWeb.ClientReadableStream<profiles_pb.UpdateSearchProfileResponse>;

  updateSearchProfile(
    request: profiles_pb.UpdateSearchProfileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: profiles_pb.UpdateSearchProfileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.profiles.v1.ProfilesService/UpdateSearchProfile',
        request,
        metadata || {},
        this.methodDescriptorUpdateSearchProfile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/UpdateSearchProfile',
    request,
    metadata || {},
    this.methodDescriptorUpdateSearchProfile);
  }

  methodDescriptorDeleteSearchProfile = new grpcWeb.MethodDescriptor(
    '/ai_poi.profiles.v1.ProfilesService/DeleteSearchProfile',
    grpcWeb.MethodType.UNARY,
    profiles_pb.DeleteSearchProfileRequest,
    profiles_pb.DeleteSearchProfileResponse,
    (request: profiles_pb.DeleteSearchProfileRequest) => {
      return request.serializeBinary();
    },
    profiles_pb.DeleteSearchProfileResponse.deserializeBinary
  );

  deleteSearchProfile(
    request: profiles_pb.DeleteSearchProfileRequest,
    metadata?: grpcWeb.Metadata | null): Promise<profiles_pb.DeleteSearchProfileResponse>;

  deleteSearchProfile(
    request: profiles_pb.DeleteSearchProfileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: profiles_pb.DeleteSearchProfileResponse) => void): grpcWeb.ClientReadableStream<profiles_pb.DeleteSearchProfileResponse>;

  deleteSearchProfile(
    request: profiles_pb.DeleteSearchProfileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: profiles_pb.DeleteSearchProfileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.profiles.v1.ProfilesService/DeleteSearchProfile',
        request,
        metadata || {},
        this.methodDescriptorDeleteSearchProfile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/DeleteSearchProfile',
    request,
    metadata || {},
    this.methodDescriptorDeleteSearchProfile);
  }

  methodDescriptorSetDefaultSearchProfile = new grpcWeb.MethodDescriptor(
    '/ai_poi.profiles.v1.ProfilesService/SetDefaultSearchProfile',
    grpcWeb.MethodType.UNARY,
    profiles_pb.SetDefaultSearchProfileRequest,
    profiles_pb.SetDefaultSearchProfileResponse,
    (request: profiles_pb.SetDefaultSearchProfileRequest) => {
      return request.serializeBinary();
    },
    profiles_pb.SetDefaultSearchProfileResponse.deserializeBinary
  );

  setDefaultSearchProfile(
    request: profiles_pb.SetDefaultSearchProfileRequest,
    metadata?: grpcWeb.Metadata | null): Promise<profiles_pb.SetDefaultSearchProfileResponse>;

  setDefaultSearchProfile(
    request: profiles_pb.SetDefaultSearchProfileRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: profiles_pb.SetDefaultSearchProfileResponse) => void): grpcWeb.ClientReadableStream<profiles_pb.SetDefaultSearchProfileResponse>;

  setDefaultSearchProfile(
    request: profiles_pb.SetDefaultSearchProfileRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: profiles_pb.SetDefaultSearchProfileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.profiles.v1.ProfilesService/SetDefaultSearchProfile',
        request,
        metadata || {},
        this.methodDescriptorSetDefaultSearchProfile,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.profiles.v1.ProfilesService/SetDefaultSearchProfile',
    request,
    metadata || {},
    this.methodDescriptorSetDefaultSearchProfile);
  }

}

