/**
 * @fileoverview gRPC-Web generated client stub for ai_poi.recents.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: recents.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.ai_poi = {};
proto.ai_poi.recents = {};
proto.ai_poi.recents.v1 = require('./recents_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai_poi.recents.v1.RecentsServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai_poi.recents.v1.RecentsServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.recents.v1.GetRecentInteractionsRequest,
 *   !proto.ai_poi.recents.v1.GetRecentInteractionsResponse>}
 */
const methodDescriptor_RecentsService_GetRecentInteractions = new grpc.web.MethodDescriptor(
  '/ai_poi.recents.v1.RecentsService/GetRecentInteractions',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.recents.v1.GetRecentInteractionsRequest,
  proto.ai_poi.recents.v1.GetRecentInteractionsResponse,
  /**
   * @param {!proto.ai_poi.recents.v1.GetRecentInteractionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.recents.v1.GetRecentInteractionsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.recents.v1.GetRecentInteractionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.recents.v1.GetRecentInteractionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.recents.v1.GetRecentInteractionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.recents.v1.RecentsServiceClient.prototype.getRecentInteractions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/GetRecentInteractions',
      request,
      metadata || {},
      methodDescriptor_RecentsService_GetRecentInteractions,
      callback);
};


/**
 * @param {!proto.ai_poi.recents.v1.GetRecentInteractionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.recents.v1.GetRecentInteractionsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.recents.v1.RecentsServicePromiseClient.prototype.getRecentInteractions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/GetRecentInteractions',
      request,
      metadata || {},
      methodDescriptor_RecentsService_GetRecentInteractions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.recents.v1.GetCityInteractionsRequest,
 *   !proto.ai_poi.recents.v1.GetCityInteractionsResponse>}
 */
const methodDescriptor_RecentsService_GetCityInteractions = new grpc.web.MethodDescriptor(
  '/ai_poi.recents.v1.RecentsService/GetCityInteractions',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.recents.v1.GetCityInteractionsRequest,
  proto.ai_poi.recents.v1.GetCityInteractionsResponse,
  /**
   * @param {!proto.ai_poi.recents.v1.GetCityInteractionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.recents.v1.GetCityInteractionsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.recents.v1.GetCityInteractionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.recents.v1.GetCityInteractionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.recents.v1.GetCityInteractionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.recents.v1.RecentsServiceClient.prototype.getCityInteractions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/GetCityInteractions',
      request,
      metadata || {},
      methodDescriptor_RecentsService_GetCityInteractions,
      callback);
};


/**
 * @param {!proto.ai_poi.recents.v1.GetCityInteractionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.recents.v1.GetCityInteractionsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.recents.v1.RecentsServicePromiseClient.prototype.getCityInteractions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/GetCityInteractions',
      request,
      metadata || {},
      methodDescriptor_RecentsService_GetCityInteractions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.recents.v1.RecordInteractionRequest,
 *   !proto.ai_poi.recents.v1.RecordInteractionResponse>}
 */
const methodDescriptor_RecentsService_RecordInteraction = new grpc.web.MethodDescriptor(
  '/ai_poi.recents.v1.RecentsService/RecordInteraction',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.recents.v1.RecordInteractionRequest,
  proto.ai_poi.recents.v1.RecordInteractionResponse,
  /**
   * @param {!proto.ai_poi.recents.v1.RecordInteractionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.recents.v1.RecordInteractionResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.recents.v1.RecordInteractionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.recents.v1.RecordInteractionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.recents.v1.RecordInteractionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.recents.v1.RecentsServiceClient.prototype.recordInteraction =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/RecordInteraction',
      request,
      metadata || {},
      methodDescriptor_RecentsService_RecordInteraction,
      callback);
};


/**
 * @param {!proto.ai_poi.recents.v1.RecordInteractionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.recents.v1.RecordInteractionResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.recents.v1.RecentsServicePromiseClient.prototype.recordInteraction =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/RecordInteraction',
      request,
      metadata || {},
      methodDescriptor_RecentsService_RecordInteraction);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.recents.v1.GetInteractionHistoryRequest,
 *   !proto.ai_poi.recents.v1.GetInteractionHistoryResponse>}
 */
const methodDescriptor_RecentsService_GetInteractionHistory = new grpc.web.MethodDescriptor(
  '/ai_poi.recents.v1.RecentsService/GetInteractionHistory',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.recents.v1.GetInteractionHistoryRequest,
  proto.ai_poi.recents.v1.GetInteractionHistoryResponse,
  /**
   * @param {!proto.ai_poi.recents.v1.GetInteractionHistoryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.recents.v1.GetInteractionHistoryResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.recents.v1.GetInteractionHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.recents.v1.GetInteractionHistoryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.recents.v1.GetInteractionHistoryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.recents.v1.RecentsServiceClient.prototype.getInteractionHistory =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/GetInteractionHistory',
      request,
      metadata || {},
      methodDescriptor_RecentsService_GetInteractionHistory,
      callback);
};


/**
 * @param {!proto.ai_poi.recents.v1.GetInteractionHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.recents.v1.GetInteractionHistoryResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.recents.v1.RecentsServicePromiseClient.prototype.getInteractionHistory =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/GetInteractionHistory',
      request,
      metadata || {},
      methodDescriptor_RecentsService_GetInteractionHistory);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.recents.v1.GetFrequentPlacesRequest,
 *   !proto.ai_poi.recents.v1.GetFrequentPlacesResponse>}
 */
const methodDescriptor_RecentsService_GetFrequentPlaces = new grpc.web.MethodDescriptor(
  '/ai_poi.recents.v1.RecentsService/GetFrequentPlaces',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.recents.v1.GetFrequentPlacesRequest,
  proto.ai_poi.recents.v1.GetFrequentPlacesResponse,
  /**
   * @param {!proto.ai_poi.recents.v1.GetFrequentPlacesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.recents.v1.GetFrequentPlacesResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.recents.v1.GetFrequentPlacesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.recents.v1.GetFrequentPlacesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.recents.v1.GetFrequentPlacesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.recents.v1.RecentsServiceClient.prototype.getFrequentPlaces =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/GetFrequentPlaces',
      request,
      metadata || {},
      methodDescriptor_RecentsService_GetFrequentPlaces,
      callback);
};


/**
 * @param {!proto.ai_poi.recents.v1.GetFrequentPlacesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.recents.v1.GetFrequentPlacesResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.recents.v1.RecentsServicePromiseClient.prototype.getFrequentPlaces =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/GetFrequentPlaces',
      request,
      metadata || {},
      methodDescriptor_RecentsService_GetFrequentPlaces);
};


module.exports = proto.ai_poi.recents.v1;

