/**
 * @fileoverview gRPC-Web generated client stub for ai_poi.recents.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: recents.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as recents_pb from './recents_pb'; // proto import: "recents.proto"


export class RecentsServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetRecentInteractions = new grpcWeb.MethodDescriptor(
    '/ai_poi.recents.v1.RecentsService/GetRecentInteractions',
    grpcWeb.MethodType.UNARY,
    recents_pb.GetRecentInteractionsRequest,
    recents_pb.GetRecentInteractionsResponse,
    (request: recents_pb.GetRecentInteractionsRequest) => {
      return request.serializeBinary();
    },
    recents_pb.GetRecentInteractionsResponse.deserializeBinary
  );

  getRecentInteractions(
    request: recents_pb.GetRecentInteractionsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<recents_pb.GetRecentInteractionsResponse>;

  getRecentInteractions(
    request: recents_pb.GetRecentInteractionsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: recents_pb.GetRecentInteractionsResponse) => void): grpcWeb.ClientReadableStream<recents_pb.GetRecentInteractionsResponse>;

  getRecentInteractions(
    request: recents_pb.GetRecentInteractionsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: recents_pb.GetRecentInteractionsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.recents.v1.RecentsService/GetRecentInteractions',
        request,
        metadata || {},
        this.methodDescriptorGetRecentInteractions,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/GetRecentInteractions',
    request,
    metadata || {},
    this.methodDescriptorGetRecentInteractions);
  }

  methodDescriptorGetCityInteractions = new grpcWeb.MethodDescriptor(
    '/ai_poi.recents.v1.RecentsService/GetCityInteractions',
    grpcWeb.MethodType.UNARY,
    recents_pb.GetCityInteractionsRequest,
    recents_pb.GetCityInteractionsResponse,
    (request: recents_pb.GetCityInteractionsRequest) => {
      return request.serializeBinary();
    },
    recents_pb.GetCityInteractionsResponse.deserializeBinary
  );

  getCityInteractions(
    request: recents_pb.GetCityInteractionsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<recents_pb.GetCityInteractionsResponse>;

  getCityInteractions(
    request: recents_pb.GetCityInteractionsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: recents_pb.GetCityInteractionsResponse) => void): grpcWeb.ClientReadableStream<recents_pb.GetCityInteractionsResponse>;

  getCityInteractions(
    request: recents_pb.GetCityInteractionsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: recents_pb.GetCityInteractionsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.recents.v1.RecentsService/GetCityInteractions',
        request,
        metadata || {},
        this.methodDescriptorGetCityInteractions,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/GetCityInteractions',
    request,
    metadata || {},
    this.methodDescriptorGetCityInteractions);
  }

  methodDescriptorRecordInteraction = new grpcWeb.MethodDescriptor(
    '/ai_poi.recents.v1.RecentsService/RecordInteraction',
    grpcWeb.MethodType.UNARY,
    recents_pb.RecordInteractionRequest,
    recents_pb.RecordInteractionResponse,
    (request: recents_pb.RecordInteractionRequest) => {
      return request.serializeBinary();
    },
    recents_pb.RecordInteractionResponse.deserializeBinary
  );

  recordInteraction(
    request: recents_pb.RecordInteractionRequest,
    metadata?: grpcWeb.Metadata | null): Promise<recents_pb.RecordInteractionResponse>;

  recordInteraction(
    request: recents_pb.RecordInteractionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: recents_pb.RecordInteractionResponse) => void): grpcWeb.ClientReadableStream<recents_pb.RecordInteractionResponse>;

  recordInteraction(
    request: recents_pb.RecordInteractionRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: recents_pb.RecordInteractionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.recents.v1.RecentsService/RecordInteraction',
        request,
        metadata || {},
        this.methodDescriptorRecordInteraction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/RecordInteraction',
    request,
    metadata || {},
    this.methodDescriptorRecordInteraction);
  }

  methodDescriptorGetInteractionHistory = new grpcWeb.MethodDescriptor(
    '/ai_poi.recents.v1.RecentsService/GetInteractionHistory',
    grpcWeb.MethodType.UNARY,
    recents_pb.GetInteractionHistoryRequest,
    recents_pb.GetInteractionHistoryResponse,
    (request: recents_pb.GetInteractionHistoryRequest) => {
      return request.serializeBinary();
    },
    recents_pb.GetInteractionHistoryResponse.deserializeBinary
  );

  getInteractionHistory(
    request: recents_pb.GetInteractionHistoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<recents_pb.GetInteractionHistoryResponse>;

  getInteractionHistory(
    request: recents_pb.GetInteractionHistoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: recents_pb.GetInteractionHistoryResponse) => void): grpcWeb.ClientReadableStream<recents_pb.GetInteractionHistoryResponse>;

  getInteractionHistory(
    request: recents_pb.GetInteractionHistoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: recents_pb.GetInteractionHistoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.recents.v1.RecentsService/GetInteractionHistory',
        request,
        metadata || {},
        this.methodDescriptorGetInteractionHistory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/GetInteractionHistory',
    request,
    metadata || {},
    this.methodDescriptorGetInteractionHistory);
  }

  methodDescriptorGetFrequentPlaces = new grpcWeb.MethodDescriptor(
    '/ai_poi.recents.v1.RecentsService/GetFrequentPlaces',
    grpcWeb.MethodType.UNARY,
    recents_pb.GetFrequentPlacesRequest,
    recents_pb.GetFrequentPlacesResponse,
    (request: recents_pb.GetFrequentPlacesRequest) => {
      return request.serializeBinary();
    },
    recents_pb.GetFrequentPlacesResponse.deserializeBinary
  );

  getFrequentPlaces(
    request: recents_pb.GetFrequentPlacesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<recents_pb.GetFrequentPlacesResponse>;

  getFrequentPlaces(
    request: recents_pb.GetFrequentPlacesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: recents_pb.GetFrequentPlacesResponse) => void): grpcWeb.ClientReadableStream<recents_pb.GetFrequentPlacesResponse>;

  getFrequentPlaces(
    request: recents_pb.GetFrequentPlacesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: recents_pb.GetFrequentPlacesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.recents.v1.RecentsService/GetFrequentPlaces',
        request,
        metadata || {},
        this.methodDescriptorGetFrequentPlaces,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.recents.v1.RecentsService/GetFrequentPlaces',
    request,
    metadata || {},
    this.methodDescriptorGetFrequentPlaces);
  }

}

