/**
 * @fileoverview gRPC-Web generated client stub for ai_poi.review.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: review.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var common_pb = require('./common_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.ai_poi = {};
proto.ai_poi.review = {};
proto.ai_poi.review.v1 = require('./review_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai_poi.review.v1.ReviewServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai_poi.review.v1.ReviewServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.review.v1.CreateReviewRequest,
 *   !proto.ai_poi.review.v1.CreateReviewResponse>}
 */
const methodDescriptor_ReviewService_CreateReview = new grpc.web.MethodDescriptor(
  '/ai_poi.review.v1.ReviewService/CreateReview',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.review.v1.CreateReviewRequest,
  proto.ai_poi.review.v1.CreateReviewResponse,
  /**
   * @param {!proto.ai_poi.review.v1.CreateReviewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.review.v1.CreateReviewResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.review.v1.CreateReviewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.review.v1.CreateReviewResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.review.v1.CreateReviewResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.review.v1.ReviewServiceClient.prototype.createReview =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/CreateReview',
      request,
      metadata || {},
      methodDescriptor_ReviewService_CreateReview,
      callback);
};


/**
 * @param {!proto.ai_poi.review.v1.CreateReviewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.review.v1.CreateReviewResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.review.v1.ReviewServicePromiseClient.prototype.createReview =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/CreateReview',
      request,
      metadata || {},
      methodDescriptor_ReviewService_CreateReview);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.review.v1.GetPOIReviewsRequest,
 *   !proto.ai_poi.review.v1.GetPOIReviewsResponse>}
 */
const methodDescriptor_ReviewService_GetPOIReviews = new grpc.web.MethodDescriptor(
  '/ai_poi.review.v1.ReviewService/GetPOIReviews',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.review.v1.GetPOIReviewsRequest,
  proto.ai_poi.review.v1.GetPOIReviewsResponse,
  /**
   * @param {!proto.ai_poi.review.v1.GetPOIReviewsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.review.v1.GetPOIReviewsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.review.v1.GetPOIReviewsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.review.v1.GetPOIReviewsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.review.v1.GetPOIReviewsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.review.v1.ReviewServiceClient.prototype.getPOIReviews =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/GetPOIReviews',
      request,
      metadata || {},
      methodDescriptor_ReviewService_GetPOIReviews,
      callback);
};


/**
 * @param {!proto.ai_poi.review.v1.GetPOIReviewsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.review.v1.GetPOIReviewsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.review.v1.ReviewServicePromiseClient.prototype.getPOIReviews =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/GetPOIReviews',
      request,
      metadata || {},
      methodDescriptor_ReviewService_GetPOIReviews);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.review.v1.GetReviewRequest,
 *   !proto.ai_poi.review.v1.GetReviewResponse>}
 */
const methodDescriptor_ReviewService_GetReview = new grpc.web.MethodDescriptor(
  '/ai_poi.review.v1.ReviewService/GetReview',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.review.v1.GetReviewRequest,
  proto.ai_poi.review.v1.GetReviewResponse,
  /**
   * @param {!proto.ai_poi.review.v1.GetReviewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.review.v1.GetReviewResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.review.v1.GetReviewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.review.v1.GetReviewResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.review.v1.GetReviewResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.review.v1.ReviewServiceClient.prototype.getReview =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/GetReview',
      request,
      metadata || {},
      methodDescriptor_ReviewService_GetReview,
      callback);
};


/**
 * @param {!proto.ai_poi.review.v1.GetReviewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.review.v1.GetReviewResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.review.v1.ReviewServicePromiseClient.prototype.getReview =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/GetReview',
      request,
      metadata || {},
      methodDescriptor_ReviewService_GetReview);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.review.v1.UpdateReviewRequest,
 *   !proto.ai_poi.review.v1.UpdateReviewResponse>}
 */
const methodDescriptor_ReviewService_UpdateReview = new grpc.web.MethodDescriptor(
  '/ai_poi.review.v1.ReviewService/UpdateReview',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.review.v1.UpdateReviewRequest,
  proto.ai_poi.review.v1.UpdateReviewResponse,
  /**
   * @param {!proto.ai_poi.review.v1.UpdateReviewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.review.v1.UpdateReviewResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.review.v1.UpdateReviewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.review.v1.UpdateReviewResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.review.v1.UpdateReviewResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.review.v1.ReviewServiceClient.prototype.updateReview =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/UpdateReview',
      request,
      metadata || {},
      methodDescriptor_ReviewService_UpdateReview,
      callback);
};


/**
 * @param {!proto.ai_poi.review.v1.UpdateReviewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.review.v1.UpdateReviewResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.review.v1.ReviewServicePromiseClient.prototype.updateReview =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/UpdateReview',
      request,
      metadata || {},
      methodDescriptor_ReviewService_UpdateReview);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.review.v1.DeleteReviewRequest,
 *   !proto.ai_poi.review.v1.DeleteReviewResponse>}
 */
const methodDescriptor_ReviewService_DeleteReview = new grpc.web.MethodDescriptor(
  '/ai_poi.review.v1.ReviewService/DeleteReview',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.review.v1.DeleteReviewRequest,
  proto.ai_poi.review.v1.DeleteReviewResponse,
  /**
   * @param {!proto.ai_poi.review.v1.DeleteReviewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.review.v1.DeleteReviewResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.review.v1.DeleteReviewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.review.v1.DeleteReviewResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.review.v1.DeleteReviewResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.review.v1.ReviewServiceClient.prototype.deleteReview =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/DeleteReview',
      request,
      metadata || {},
      methodDescriptor_ReviewService_DeleteReview,
      callback);
};


/**
 * @param {!proto.ai_poi.review.v1.DeleteReviewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.review.v1.DeleteReviewResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.review.v1.ReviewServicePromiseClient.prototype.deleteReview =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/DeleteReview',
      request,
      metadata || {},
      methodDescriptor_ReviewService_DeleteReview);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.review.v1.GetUserReviewsRequest,
 *   !proto.ai_poi.review.v1.GetUserReviewsResponse>}
 */
const methodDescriptor_ReviewService_GetUserReviews = new grpc.web.MethodDescriptor(
  '/ai_poi.review.v1.ReviewService/GetUserReviews',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.review.v1.GetUserReviewsRequest,
  proto.ai_poi.review.v1.GetUserReviewsResponse,
  /**
   * @param {!proto.ai_poi.review.v1.GetUserReviewsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.review.v1.GetUserReviewsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.review.v1.GetUserReviewsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.review.v1.GetUserReviewsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.review.v1.GetUserReviewsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.review.v1.ReviewServiceClient.prototype.getUserReviews =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/GetUserReviews',
      request,
      metadata || {},
      methodDescriptor_ReviewService_GetUserReviews,
      callback);
};


/**
 * @param {!proto.ai_poi.review.v1.GetUserReviewsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.review.v1.GetUserReviewsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.review.v1.ReviewServicePromiseClient.prototype.getUserReviews =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/GetUserReviews',
      request,
      metadata || {},
      methodDescriptor_ReviewService_GetUserReviews);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.review.v1.LikeReviewRequest,
 *   !proto.ai_poi.review.v1.LikeReviewResponse>}
 */
const methodDescriptor_ReviewService_LikeReview = new grpc.web.MethodDescriptor(
  '/ai_poi.review.v1.ReviewService/LikeReview',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.review.v1.LikeReviewRequest,
  proto.ai_poi.review.v1.LikeReviewResponse,
  /**
   * @param {!proto.ai_poi.review.v1.LikeReviewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.review.v1.LikeReviewResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.review.v1.LikeReviewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.review.v1.LikeReviewResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.review.v1.LikeReviewResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.review.v1.ReviewServiceClient.prototype.likeReview =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/LikeReview',
      request,
      metadata || {},
      methodDescriptor_ReviewService_LikeReview,
      callback);
};


/**
 * @param {!proto.ai_poi.review.v1.LikeReviewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.review.v1.LikeReviewResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.review.v1.ReviewServicePromiseClient.prototype.likeReview =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/LikeReview',
      request,
      metadata || {},
      methodDescriptor_ReviewService_LikeReview);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.review.v1.ReportReviewRequest,
 *   !proto.ai_poi.review.v1.ReportReviewResponse>}
 */
const methodDescriptor_ReviewService_ReportReview = new grpc.web.MethodDescriptor(
  '/ai_poi.review.v1.ReviewService/ReportReview',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.review.v1.ReportReviewRequest,
  proto.ai_poi.review.v1.ReportReviewResponse,
  /**
   * @param {!proto.ai_poi.review.v1.ReportReviewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.review.v1.ReportReviewResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.review.v1.ReportReviewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.review.v1.ReportReviewResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.review.v1.ReportReviewResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.review.v1.ReviewServiceClient.prototype.reportReview =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/ReportReview',
      request,
      metadata || {},
      methodDescriptor_ReviewService_ReportReview,
      callback);
};


/**
 * @param {!proto.ai_poi.review.v1.ReportReviewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.review.v1.ReportReviewResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.review.v1.ReviewServicePromiseClient.prototype.reportReview =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/ReportReview',
      request,
      metadata || {},
      methodDescriptor_ReviewService_ReportReview);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai_poi.review.v1.GetReviewStatisticsRequest,
 *   !proto.ai_poi.review.v1.GetReviewStatisticsResponse>}
 */
const methodDescriptor_ReviewService_GetReviewStatistics = new grpc.web.MethodDescriptor(
  '/ai_poi.review.v1.ReviewService/GetReviewStatistics',
  grpc.web.MethodType.UNARY,
  proto.ai_poi.review.v1.GetReviewStatisticsRequest,
  proto.ai_poi.review.v1.GetReviewStatisticsResponse,
  /**
   * @param {!proto.ai_poi.review.v1.GetReviewStatisticsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai_poi.review.v1.GetReviewStatisticsResponse.deserializeBinary
);


/**
 * @param {!proto.ai_poi.review.v1.GetReviewStatisticsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai_poi.review.v1.GetReviewStatisticsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai_poi.review.v1.GetReviewStatisticsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai_poi.review.v1.ReviewServiceClient.prototype.getReviewStatistics =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/GetReviewStatistics',
      request,
      metadata || {},
      methodDescriptor_ReviewService_GetReviewStatistics,
      callback);
};


/**
 * @param {!proto.ai_poi.review.v1.GetReviewStatisticsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai_poi.review.v1.GetReviewStatisticsResponse>}
 *     Promise that resolves to the response
 */
proto.ai_poi.review.v1.ReviewServicePromiseClient.prototype.getReviewStatistics =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai_poi.review.v1.ReviewService/GetReviewStatistics',
      request,
      metadata || {},
      methodDescriptor_ReviewService_GetReviewStatistics);
};


module.exports = proto.ai_poi.review.v1;

