/**
 * @fileoverview gRPC-Web generated client stub for ai_poi.statistics.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.32.0
// source: statistics.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as statistics_pb from './statistics_pb'; // proto import: "statistics.proto"


export class StatisticsServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetMainPageStatistics = new grpcWeb.MethodDescriptor(
    '/ai_poi.statistics.v1.StatisticsService/GetMainPageStatistics',
    grpcWeb.MethodType.UNARY,
    statistics_pb.GetMainPageStatisticsRequest,
    statistics_pb.GetMainPageStatisticsResponse,
    (request: statistics_pb.GetMainPageStatisticsRequest) => {
      return request.serializeBinary();
    },
    statistics_pb.GetMainPageStatisticsResponse.deserializeBinary
  );

  getMainPageStatistics(
    request: statistics_pb.GetMainPageStatisticsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<statistics_pb.GetMainPageStatisticsResponse>;

  getMainPageStatistics(
    request: statistics_pb.GetMainPageStatisticsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: statistics_pb.GetMainPageStatisticsResponse) => void): grpcWeb.ClientReadableStream<statistics_pb.GetMainPageStatisticsResponse>;

  getMainPageStatistics(
    request: statistics_pb.GetMainPageStatisticsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: statistics_pb.GetMainPageStatisticsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.statistics.v1.StatisticsService/GetMainPageStatistics',
        request,
        metadata || {},
        this.methodDescriptorGetMainPageStatistics,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.statistics.v1.StatisticsService/GetMainPageStatistics',
    request,
    metadata || {},
    this.methodDescriptorGetMainPageStatistics);
  }

  methodDescriptorStreamMainPageStatistics = new grpcWeb.MethodDescriptor(
    '/ai_poi.statistics.v1.StatisticsService/StreamMainPageStatistics',
    grpcWeb.MethodType.SERVER_STREAMING,
    statistics_pb.StreamMainPageStatisticsRequest,
    statistics_pb.StatisticsEvent,
    (request: statistics_pb.StreamMainPageStatisticsRequest) => {
      return request.serializeBinary();
    },
    statistics_pb.StatisticsEvent.deserializeBinary
  );

  streamMainPageStatistics(
    request: statistics_pb.StreamMainPageStatisticsRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<statistics_pb.StatisticsEvent> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/ai_poi.statistics.v1.StatisticsService/StreamMainPageStatistics',
      request,
      metadata || {},
      this.methodDescriptorStreamMainPageStatistics);
  }

  methodDescriptorGetDetailedPOIStatistics = new grpcWeb.MethodDescriptor(
    '/ai_poi.statistics.v1.StatisticsService/GetDetailedPOIStatistics',
    grpcWeb.MethodType.UNARY,
    statistics_pb.GetDetailedPOIStatisticsRequest,
    statistics_pb.GetDetailedPOIStatisticsResponse,
    (request: statistics_pb.GetDetailedPOIStatisticsRequest) => {
      return request.serializeBinary();
    },
    statistics_pb.GetDetailedPOIStatisticsResponse.deserializeBinary
  );

  getDetailedPOIStatistics(
    request: statistics_pb.GetDetailedPOIStatisticsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<statistics_pb.GetDetailedPOIStatisticsResponse>;

  getDetailedPOIStatistics(
    request: statistics_pb.GetDetailedPOIStatisticsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: statistics_pb.GetDetailedPOIStatisticsResponse) => void): grpcWeb.ClientReadableStream<statistics_pb.GetDetailedPOIStatisticsResponse>;

  getDetailedPOIStatistics(
    request: statistics_pb.GetDetailedPOIStatisticsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: statistics_pb.GetDetailedPOIStatisticsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.statistics.v1.StatisticsService/GetDetailedPOIStatistics',
        request,
        metadata || {},
        this.methodDescriptorGetDetailedPOIStatistics,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.statistics.v1.StatisticsService/GetDetailedPOIStatistics',
    request,
    metadata || {},
    this.methodDescriptorGetDetailedPOIStatistics);
  }

  methodDescriptorGetLandingPageStatistics = new grpcWeb.MethodDescriptor(
    '/ai_poi.statistics.v1.StatisticsService/GetLandingPageStatistics',
    grpcWeb.MethodType.UNARY,
    statistics_pb.GetLandingPageStatisticsRequest,
    statistics_pb.GetLandingPageStatisticsResponse,
    (request: statistics_pb.GetLandingPageStatisticsRequest) => {
      return request.serializeBinary();
    },
    statistics_pb.GetLandingPageStatisticsResponse.deserializeBinary
  );

  getLandingPageStatistics(
    request: statistics_pb.GetLandingPageStatisticsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<statistics_pb.GetLandingPageStatisticsResponse>;

  getLandingPageStatistics(
    request: statistics_pb.GetLandingPageStatisticsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: statistics_pb.GetLandingPageStatisticsResponse) => void): grpcWeb.ClientReadableStream<statistics_pb.GetLandingPageStatisticsResponse>;

  getLandingPageStatistics(
    request: statistics_pb.GetLandingPageStatisticsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: statistics_pb.GetLandingPageStatisticsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.statistics.v1.StatisticsService/GetLandingPageStatistics',
        request,
        metadata || {},
        this.methodDescriptorGetLandingPageStatistics,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.statistics.v1.StatisticsService/GetLandingPageStatistics',
    request,
    metadata || {},
    this.methodDescriptorGetLandingPageStatistics);
  }

  methodDescriptorGetUserActivityAnalytics = new grpcWeb.MethodDescriptor(
    '/ai_poi.statistics.v1.StatisticsService/GetUserActivityAnalytics',
    grpcWeb.MethodType.UNARY,
    statistics_pb.GetUserActivityAnalyticsRequest,
    statistics_pb.GetUserActivityAnalyticsResponse,
    (request: statistics_pb.GetUserActivityAnalyticsRequest) => {
      return request.serializeBinary();
    },
    statistics_pb.GetUserActivityAnalyticsResponse.deserializeBinary
  );

  getUserActivityAnalytics(
    request: statistics_pb.GetUserActivityAnalyticsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<statistics_pb.GetUserActivityAnalyticsResponse>;

  getUserActivityAnalytics(
    request: statistics_pb.GetUserActivityAnalyticsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: statistics_pb.GetUserActivityAnalyticsResponse) => void): grpcWeb.ClientReadableStream<statistics_pb.GetUserActivityAnalyticsResponse>;

  getUserActivityAnalytics(
    request: statistics_pb.GetUserActivityAnalyticsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: statistics_pb.GetUserActivityAnalyticsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.statistics.v1.StatisticsService/GetUserActivityAnalytics',
        request,
        metadata || {},
        this.methodDescriptorGetUserActivityAnalytics,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.statistics.v1.StatisticsService/GetUserActivityAnalytics',
    request,
    metadata || {},
    this.methodDescriptorGetUserActivityAnalytics);
  }

  methodDescriptorGetSystemAnalytics = new grpcWeb.MethodDescriptor(
    '/ai_poi.statistics.v1.StatisticsService/GetSystemAnalytics',
    grpcWeb.MethodType.UNARY,
    statistics_pb.GetSystemAnalyticsRequest,
    statistics_pb.GetSystemAnalyticsResponse,
    (request: statistics_pb.GetSystemAnalyticsRequest) => {
      return request.serializeBinary();
    },
    statistics_pb.GetSystemAnalyticsResponse.deserializeBinary
  );

  getSystemAnalytics(
    request: statistics_pb.GetSystemAnalyticsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<statistics_pb.GetSystemAnalyticsResponse>;

  getSystemAnalytics(
    request: statistics_pb.GetSystemAnalyticsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: statistics_pb.GetSystemAnalyticsResponse) => void): grpcWeb.ClientReadableStream<statistics_pb.GetSystemAnalyticsResponse>;

  getSystemAnalytics(
    request: statistics_pb.GetSystemAnalyticsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: statistics_pb.GetSystemAnalyticsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ai_poi.statistics.v1.StatisticsService/GetSystemAnalytics',
        request,
        metadata || {},
        this.methodDescriptorGetSystemAnalytics,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ai_poi.statistics.v1.StatisticsService/GetSystemAnalytics',
    request,
    metadata || {},
    this.methodDescriptorGetSystemAnalytics);
  }

}

